### ISSUE TITLE
[Ride Homepage] Check the way of establishing of User stops of the ride by the way of choosing address without street number.

### ISSUE THREAD

**Issue by Mariana0105** [ita-social-projects/SoftServeCar-Back-End#1004]
Environment: Android 8.0, HUAWEI P8.
Reproducible: always.
Build found: v1.0.529

Preconditions:
1. The 'Car' app is opened.
2. User is logged in.
3. 'Ride Homepage' is opened. 

Steps to reproduce:
1. Go to 'Add a Ride'.
2. Fill in the 'From/To' search boxes (e.g. 'Fron'-Vul.Stryyska , Lviv; 'To'-Volodymyra Velykoho, Lviv) and tap 'Confirm'.
3. Set departure time, ride type, fee and tap the 'Publish' button.
4. Tap the recently created ride under 'Upcoming' on the 'Ride Homepage' to observe ride details.

Actual result:
The ride route is established by the way of choosing the address directions without street numbers. User stops are automatically chosen with Google maps. User stops might be inaccurate.

Expected result:
User stops chosen with Google maps match User's required route. User can see that the map shows the stops necessary for him/her.

Labels to be added
"Bug" ("bug"), Priority ("pri: medium")

![зображення_2022-02-01_002531](https://user-images.githubusercontent.com/96290387/151883321-cbb84a1d-5252-4408-b5a0-13c59d56005e.png)

**Comment by nrevutska** [comment]
Not a problem
