### ISSUE TITLE
[Invitation] The information about the number of made rides is too close to the invitation separator.

### ISSUE THREAD

**Issue by Mariana0105** [ita-social-projects/SoftServeCar-Back-End#1025]
Environment: Android 8.0, HUAWEI P8.
Reproducible: always.
Build found: v1.0.539

Preconditions:
User is logged in as a passenger and got an invitation for a ride. 'Ride Homepage' is opened.

Steps to reproduce:
1. Go to 'Notifications';
2. Tap on the 'Notificarions' tab to open it.
3. Open the recieved ride invitation by tapping.
4. Verify that information about the number of made rides is far enough from the separator.

Actual result:
The information about the number of made rides is too close to the separator.

Expected result:
The information about the number of made rides is far enough from the separator.

User story and test case links:
E.g.: "User story 
[Test case](https://jira.softserve.academy/browse/100)"

Labels to be added:
"Bug" ("bug"), Priority ("pri: low")

![зображення_2022-02-07_062909](https://user-images.githubusercontent.com/96290387/152724641-42cd2081-1897-40a8-b120-60e9dbdec332.png)

**Comment by RomanVynarovych** [comment]
Implemented
