### ISSUE TITLE
[Ride Homepage] Requested rides are shown incorrectly without the information about their ride routes

### ISSUE THREAD

**Issue by chelaak** [ita-social-projects/SoftServeCar-Back-End#1064]
Environment: Samsung S10, Android 9.0
Reproducible: always.
Build found: [v1.0.574.apk](https://github.com/ita-social-projects/Car-Front-End/suites/5750896318/artifacts/190988523)

**Preconditions:**
1. The 'Car' application is opened.
2. The user is logged in.
3. The 'Ride Request' is already created (e.g. Naukova Street, Lviv - Mytna Square, Lviv)
4. The 'Ride Homepage' is opened.

**Steps to reproduce**
1. The 'Ride Homepage' is opened.
2. Go to the 'Requested' tab.
3. Take a look at the previously created 'Ride request'
4. Try to click on it
5. Try to view stops

**Actual result**
The requested ride is not clickable and the information about the ride route is not available
![req](https://user-images.githubusercontent.com/95219683/159575217-d337122e-bde9-4b3f-a6e7-ea2afbfe73ea.png)

**Expected result**
The requested ride should be clickable and should be with information about the ride route.
When the user clicks on it the page with stops should be opened.

**User story and test case links**
User Story #245

**Labels to be added**
"Bug" ("bug"), Priority ("pri:high ")

**Comment by VitaliiOryshchyn** [comment]
it's fixed)
