### ISSUE TITLE
[Input Address] Search doesn't work correctly

### ISSUE THREAD

**Issue by chelaak** [ita-social-projects/SoftServeCar-Back-End#1065]
Environment: Samsung S10, Android 9.0
Reproducible: always.
Build found: [v1.0.574.apk](https://github.com/ita-social-projects/Car-Front-End/suites/5750896318/artifacts/190988523)

**Preconditions**
1. The 'Car' application is opened.
2. The user is logged in.

**Steps to reproduce**
1. The 'Cars Homepage' is opened
1. Click on the 'Add a Ride'
2. Click on the 'From' 'To'  textbox and input any data (e.g. Shevchenka street)
3. Try to mark the location

**Actual result**
The search does not work correctly, the dropdown menu is not opened.
The user can't mark the location.
![image](https://user-images.githubusercontent.com/95219683/159582317-58a95a0f-40e2-420e-b71e-4a8ffae1bb6a.png)

**Expected result**
The search should help with inputting the data, the dropdown menu should be opened.
Users should be able to mark the location manually.

**User story**
#24

**Labels to be added**
"Bug" ("bug"), Priority ("pri:high ")

**Comment by VitaliiOryshchyn** [comment]
it's fixed)
