### ISSUE TITLE
[Invitation] User's personal data from notification is demonstrated without 'Badges' information.

### ISSUE THREAD

**Issue by chelaak** [ita-social-projects/SoftServeCar-Back-End#1081]
**Environment:** Android 12, Nexus 5X.
**Reproducible:** always.
**Build found:** [v1.0.591.apk](https://github.com/ita-social-projects/Car-Front-End/suites/5973617974/artifacts/205556003)

**Preconditions:**
1. The 'Car' app is opened.
2. The user is logged in.
3. The ride (e.g. From: Lviv, To: Kyiv, 08.04, 01:28, Fee: Free) is created and the SoftServian is invited 
5. The user (passenger) is logged in to the application.

**Steps to reproduce**
1. Log in to the 'Car' application as a passenger
2. Go to the 'Notifications' page
3. Tap the new 'Journey invitation' notification
4. Take a look at the Driver's personal data

**Actual result**
Applicant's personal data consists of: applicant's photo, Name & Surname (N&S), SS position, number of previous rides through App, without information about user's badges.

**Expected result**
Applicant's personal data should consist of: applicant's photo, Name & Surname (N&S), SS position, the number of previous rides through App and information about user's badges with valid values according to the requirements.
![chrome_8Mb7XgXxqt](https://user-images.githubusercontent.com/95219683/162841029-893f6237-c150-4782-9efe-d06574ad9253.png)

User story: #418 

**Labels to be added**
"Bug" ("bug"), Priority ("pri:low ")

**Comment by MaksymTertychnyj** [comment]
bug not
