### ISSUE TITLE
[Address Book] Add a mockup to create a name for the Address after choosing point in the map.

### ISSUE THREAD

**Issue by NazariiChetvertukha** [ita-social-projects/SoftServeCar-Back-End#221]
User (Driver/Passenger) shall add a name for his address during adding a new item for his Address Book.

**Comment by OlenaBobalo** [comment]
@NazariyChetvertukha Please clarify the task: Why User needs to create a name for the address choosing IN THE MAP? (why they need a map for a name creation?)

**Comment by NazariiChetvertukha** [comment]
@OlenaBobalo  Actually, we don't need a map to add the name to the point on the map, but, I think, it will be looking "more naturally" for the User when he adds a name right after choosing the point (maybe below the address box on the mockup). It is not a requirement.
