### ISSUE TITLE
Width of messages

### ISSUE THREAD

**Issue by RamzesUAA** [ita-social-projects/SoftServeCar-Back-End#225]
How the width of messages should be formed. What is min-width and what is the max-width
![image](https://user-images.githubusercontent.com/58659160/107616025-e41c1e00-6c55-11eb-919e-850d645a7f8b.png)

**Comment by OlenaBobalo** [comment]
@RamzesUAA Please watch US#45. It's written there in the "Assumptions & Constrains" block.
