### ISSUE TITLE
'Add a car' changing 'Brand'\'Model' fields

### ISSUE THREAD

**Issue by MarianKornaha** [ita-social-projects/SoftServeCar-Back-End#240]
Environment: Asus ROG Phone 2, Android 9.
Reproducible: Always reproduce
Build v1.0.47

Preconditions:
Enable internet connection, login to our account.

Steps to reproduce:
1. Go to 'My Profile'
2. Click on 'Your cars'
3. Click on 'Add a car'
4. Click on 'Brand'
5. Choose any brand
6. Click on 'Model'
7. Choose any model
8. Click on 'Brand'
9. Choose another brand

**Actual result**

After changing 'Brand' field, field 'Model' staying with the same statement.

**Expected result**
After changing 'Brand' field, field 'Model' should be cleared.

User story links:
https://github.com/ita-social-projects/Car-Back-End/issues/33

Priority: High
![482eced0-248f-4c8f-a743-dc5b91d9aa7f (1)](https://user-images.githubusercontent.com/78917960/108365157-8eb8b180-71ff-11eb-8771-5c4cded2709a.jpg)
![482eced0-248f-4c8f-a743-dc5b91d9aa7f](https://user-images.githubusercontent.com/78917960/108365159-8f514800-71ff-11eb-9727-41abe06a5af9.jpg)

**Comment by strelovidniy** [comment]
Fixed by TetianaLysak
