### ISSUE TITLE
[Installing app] New installation of v1.0.47 impossible, only renew of previous version 

### ISSUE THREAD

**Issue by zxmiron** [ita-social-projects/SoftServeCar-Back-End#241]
**Environment:** Android 9, Samsung SM-A530F.
**Reproducible:** always
**Build found:** https://github.com/ita-social-projects/Car-Front-End/actions/runs/577395807

**Preconditions**
Don't install app version 1.0.47 before uninstalling of version 1.0.46.
Uninstall version 1.0.46

**Steps to reproduce**
1. Load new zip from https://github.com/ita-social-projects/Car-Front-End/actions/runs/577395807 by [link ](https://github.com/ita-social-projects/Car-Front-End/suites/2066460978/artifacts/41743907)
2. Unpack it
3. Launch app-release.apk
4. Press "Установити" when system informs about app permissions

**Actual result**
Appears message that app wasn't installed 
![image](https://user-images.githubusercontent.com/78938450/108368562-469b8e00-7203-11eb-9e7f-ff4512205c7b.png)

**Expected result**
Appears message that app installed successfully

**Comments**
If you install 1.0.47 on existing 1.0.46 - it installs like an update, bug doesn't reproduce
If you install 1.0.47, uninstall it and install again - it installs normally and bug doesn't reproduce

**Postconditions**

**User story and test case links**

**Labels to be added**
"Bug" ("bug"), Priority ("pri: medium ")

**Comment by strelovidniy** [comment]
Clear storage & install last build
