### ISSUE TITLE
Changing\Updating your car in 'Your cars'

### ISSUE THREAD

**Issue by MarianKornaha** [ita-social-projects/SoftServeCar-Back-End#248]
Environment: Android 9, 10. Asus ROG Phone 2, Black Shark 1.
Reproducible: always.
Build found: v1.0.51
Preconditions: Login to our acc, enable the internet connection, already added car into 'Your cars'

Steps to reproduce:
1. Go to 'Your cars'
2. Click on already created car
3. Change all specifications
4. Click on 'SAVE'

Actual result:
After click on 'SAVE' button application is crushing

Expected result
After click on 'SAVE' button, all changes must be saved.

User story: https://github.com/ita-social-projects/Car-Back-End/issues/53

https://user-images.githubusercontent.com/78917960/108502944-48755800-72bc-11eb-9608-4216a692eaf4.mp4

**Comment by TetianaLysak** [comment]
This component is still in progress
![image](https://user-images.githubusercontent.com/73545111/108513716-a2c9e500-72cb-11eb-9844-5f7947953a77.png)
