### ISSUE TITLE
A new car record is shown after re-opening the "Your cars" page

### ISSUE THREAD

**Issue by Vladyslava95** [ita-social-projects/SoftServeCar-Back-End#249]
https://user-images.githubusercontent.com/71496479/108511785-0868a200-72c9-11eb-8939-687ce9374f46.mp4

**Environment:**  Android 11, Samsung Galaxy S10e.
**Reproducible:** always.
**Build found:** 1.0.51

**Preconditions**
The "Car" app is opened
The "My Profile" page is opened

**Steps to reproduce**
1. Open the "Your car" page
2. Click on the  "Add a car" button at the bottom of the page
3. Entered all required information with valid data
4. Click on the "Save" button
5. Click on the "Back" button
6. Re-open the "Your cars" page.
7. Observe the result

**Actual result**
A new car record is shown after re-opening the "Your cars" page

**Expected result**
A new car record is shown after clicking the "Save" button in the "Your car" list.

**User story and test case links**
"User story #33

**Labels to be added**
"Bug" ("bug"), Priority ("pri: high")

**Comment by strelovidniy** [comment]
Fixed by TetianaLysak
