### ISSUE TITLE
400 error if '*' fields are empty in 'Add a car' function

### ISSUE THREAD

**Issue by MarianKornaha** [ita-social-projects/SoftServeCar-Back-End#252]
Environment: Asus ROG Phone 2, Android 9.
Reproducible: Always reproduce
Build v1.0.51

Preconditions:
Enable internet connection, log in to our account.

Steps to reproduce
1. Go to 'My profile'
2. Click on 'Add a car'
3. Fill in not all fields with '*'
4. Click on 'SAVE' button

Actual result
We got a page with 400error(Internal Server Error)

Expected result
We have to get a pop-up window with some information like 'Fill in all '*' fields'

User story https://github.com/ita-social-projects/Car-Back-End/issues/33

https://user-images.githubusercontent.com/78917960/108526202-83d24f80-72d9-11eb-96a3-1eda3ff65112.mp4

**Comment by strelovidniy** [comment]
Fixed by TetianaLysak
