### ISSUE TITLE
 [My Profile] Internet connection fail when we try to save photo in "My Profile/Settings"

### ISSUE THREAD

**Issue by MarianKornaha** [ita-social-projects/SoftServeCar-Back-End#282]
**Environment:** Android 9, Asus ROG Phone 2
**Reproducible:** always
**Build found:** 1.0.70
**Preconditions**
1. Check internet connection
2. Run Car application 
3. Log in to your account

**Steps to reproduce**
1. Go to 'My Profile'
2. Click on 'Settings'
3. Click to "CHANGE PHOTO"
4. Upload a photo
5. Click "SAVE"

**Actual result**
The photo is not saved and we got a pop-up error message

**Expected result**
Photo uploaded and saved

**User story and test case links**
https://github.com/ita-social-projects/Car-Back-End/issues/32

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

**Comment by AnnaBalah** [comment]
This bug is not reproducible anymore.
