### ISSUE TITLE
[My Profile] Internet connection fail when we try to save photo in "My Profile/Settings"

### ISSUE THREAD

**Issue by MarianKornaha** [ita-social-projects/SoftServeCar-Back-End#283]
**Environment:** Android 9, Asus ROG Phone 2
**Reproducible:** always
**Build found:** 1.0.70
**Preconditions**
1. Check internet connection
2. Run Car application 
3. Log in to your account

**Steps to reproduce**
1. Go to 'My Profile'
2. Click on 'Settings'
3. Click to "CHANGE PHOTO"
4. Upload a photo
5. Click "SAVE"

**Actual result**
Photo is not saved and we got a pop-up error message(look attachments)

**Expected result**
Photo uploaded and saved

**User story and test case links**
https://github.com/ita-social-projects/Car-Back-End/issues/32
https://github.com/ita-social-projects/Car-Back-End/issues/18

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")
![Screenshot_20210301-150024661](https://user-images.githubusercontent.com/78917960/109502105-386e2d00-7aa1-11eb-966f-1be63b56083f.jpg)

**Comment by bohatyrov** [comment]
Can`t reproduce
