### ISSUE TITLE
[Journey Homepage] Label text 'CREATE A JOURNEY' is splitted

### ISSUE THREAD

**Issue by zxmiron** [ita-social-projects/SoftServeCar-Back-End#297]
Environment: Android 9, Samsung SM-A530F (screen size 2220x1080); iOS 14.1, iPhone 7 (appetize.io emulator)
Reproducible: always
Build found: build 1.0.77

**Preconditions**
Launch app or open Journey Homepage

**Steps to reproduce**
1. Verify label 'CREATE A JOURNEY'

**Actual result**
Label 'CREATE A JOURNEY' words are splitted to 'CREA TE A JOUR NEY'
![image](https://user-images.githubusercontent.com/78938450/109867864-acf6c680-7c6f-11eb-9071-c2e8c69370ae.png)

**Expected result**
Words on the label should be unsplitted. 

**User story and test case links**
User story #23 

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

**Comment by zxmiron** [comment]
not fixed

**Comment by SashaOsypova** [comment]
Label 'Create a journey' isn't actual anymore.
"Add a ride" is shown now. Build 1.0.153
