### ISSUE TITLE
[Add Car] The "Brand", "Models", "Colors" dropdown items are displayed under the dropdowns.

### ISSUE THREAD

**Issue by Vladyslava95** [ita-social-projects/SoftServeCar-Back-End#298]
**Environment:**  iPhone 12 Pro Max, OS 14.2
**Reproducible:** always
**Build found:**  build 1.0.77 

**Preconditions**
The "Car" bug is opened
The 'My Profile' page is opened

**Steps to reproduce**
1. Go to the "Add Cars" page
2. Select the "Brand" dropdown
3. Pay attention to the dropdown items

**Actual result**
The "Brand", "Models", "Colors" dropdown items are displayed under the dropdowns.

**Expected result**
The "Brand", "Models", "Colors" dropdown items are displayed over the dropdowns.

**User story and test case links**
E.g.: "User story #33

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

**Comment by Vladyslava95** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/71496479/109872561-44124d00-7c75-11eb-81de-79d0af9f6b59.png)

**Comment by volodymyrRuban1** [comment]
Fixed https://github.com/ita-social-projects/Car-Front-End/pull/586
