### ISSUE TITLE
[Journey Homepage] Manage journeys buttons aren't aligned

### ISSUE THREAD

**Issue by zxmiron** [ita-social-projects/SoftServeCar-Back-End#302]
Environment: Android 9, Samsung SM-A530F (screen size 2220x1080)
Reproducible: always
Build found: build 1.0.77

**Preconditions**
Launch app or open Journey Homepage

**Steps to reproduce**
1. Verify alignment of Manage journeys buttons: 'ALL', 'PAST', 'UPCOMING', 'SCHEDULED'

**Actual result**
Interval between buttons isn't equal.
Buttons aren't aligned to screen width
![image](https://user-images.githubusercontent.com/78938450/109878117-812e0d80-7c7c-11eb-8828-2eefa9671ad4.png)

**Expected result**
Interval between buttons should be equal.
Buttons should be aligned to screen width despite the attached mockup in US #23 

**User story and test case links**
User story #23 

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

**Comment by SashaOsypova** [comment]
Isn't reproduced on Samsung SM-A530F (android 11), Samsung Galaxy A51. App version 1.0.153

**Comment by ivanstrilchuk** [comment]
Build: v.1.0.253
Environment: Android 10 (Pixel 4 XL), Android 8.1 (Nexus7), Android 10 (Nexus 5)
Reproducible: always

Preconditions:
- Launch app or open 'Ride' homepage

Steps to reproduce:
- Verify alignment of Manage journeys buttons: 'ALL', 'PAST', 'UPCOMING', 'REGULAR'

Expected result:
- The same aligning distance between 'ALL', 'PAST', 'UPCOMING', 'REGULAR' buttons

Actual result:
- Different aligning distance between 'ALL', 'PAST', 'UPCOMING', 'REGULAR' buttons
![#302 Nexus5 Android10 cut](https://user-images.githubusercontent.com/87978779/128676050-d64c752c-3e59-4283-ad0d-e40e0b10c2ef.jpg)
![#302 Pixel4 Android10 cut](https://user-images.githubusercontent.com/87978779/128676079-0ebfe631-98f5-43c1-9631-1aa46183fda4.jpg)
![#302 Android 10 (Pixel 4 XL)](https://user-images.githubusercontent.com/87978779/128676216-34b2e59a-ee41-49df-8886-83329e5403de.jpg)
