### ISSUE TITLE
[Create Car] Cant add new car, "Plate number is not valid" error message

### ISSUE THREAD

**Issue by MarianKornaha** [ita-social-projects/SoftServeCar-Back-End#306]
**Environment:** Android 9, Asus ROG Phone 2
**Reproducible:** always
**Build found:** 1.0.79
**Preconditions**
1. Check internet connection
2. Run Car application
3. Log in to your account

**Steps to reproduce**
1. Go to 'My Profile'
2. Click on 'Your cars'
3.  Click on 'Add a car'
4.  Set correct values in all fields
5. Click 'SAVE'

**Actual result**
Error message "Plate number is not valid" is displayed

**Expected result**
New car saved and added into "Your Cars"

**User story**
https://github.com/ita-social-projects/Car-Back-End/issues/33
**Labels to be added**
![add car](https://user-images.githubusercontent.com/78917960/110084818-0dcdee00-7d99-11eb-9778-5ddfcaf7d837.jpg)

**Comment by EdgeOfMordor** [comment]
Cannot reproduce
