### ISSUE TITLE
[Journey Homepage] App crashes when tap 'Search for a journey' label

### ISSUE THREAD

**Issue by zxmiron** [ita-social-projects/SoftServeCar-Back-End#307]
Environment: iOS 14.1, iPhone 11 Pro Max (appetize.io emulator)
Reproducible: always
Build found: build 1.0.80

**Preconditions**
Launch app or open Journey Homepage

**Steps to reproduce**
1. Tap 'Search for a journey' label

**Actual result**
App closes

**Expected result**
'Search for a journey' page should be opened

**User story and test case links**
"User story #23

**Comment by strelovidniy** [comment]
Maps on IOS not implemented yet

**Comment by zxmiron** [comment]
not fixed
would be nice to make a stub here
