### ISSUE TITLE
[Address book page] App crashes when tap 'Add new Address'

### ISSUE THREAD

**Issue by zxmiron** [ita-social-projects/SoftServeCar-Back-End#308]
Environment: iOS 14.1, iPhone 11 Pro Max (appetize.io emulator)
Reproducible: always
Build found: build 1.0.80

**Preconditions**
1. Open 'My profile' homepage
2. Tap 'Address book'

**Steps to reproduce**
1. Tap 'Add new Address'

**Actual result**
App closes

**Expected result**
'Add Address' page should be opened

**User story and test case links**
User story #31

**Comment by strelovidniy** [comment]
Maps on IOS not implemented yet
