### ISSUE TITLE
[Settings] No progress indication for Profile photo uploading 

### ISSUE THREAD

**Issue by Vladyslava95** [ita-social-projects/SoftServeCar-Back-End#315]
**Reproducible:** always, also for "Delete photo", "Change photo"
**Build found:**  build 1.0.85
**Preconditions**
The "Car" app is opened
The "My Profile" page is opened

**Steps to reproduce**
1. Go to  the 'Settings' page
2. Click on button with photo details and choose 'Add photo'
3. Choose photo to upload
4. Observe the result

**Actual result**
The avatar photo takes a long time to upload without any indication. (Please see comments below for videos.)

**Expected result**
There is indication bar, that photo is uploading.

**Comment by Vladyslava95** [comment]
https://user-images.githubusercontent.com/71496479/110694130-ecce2880-81f0-11eb-8ee7-cfe93cd23ebe.mp4

**Comment by AnnaBalah** [comment]
**Environment:** Redmi Note 9 Pro, Android 12.0.3, app version 1.0.140 
I investigated this issue and found, change of photo does not depend on closing the app, it just take a lot of time to update. 
Maybe it will be better to add some sort of progress indicator?

https://user-images.githubusercontent.com/81674765/116790197-bc518f00-aabb-11eb-85a4-524fe3ee522e.mp4


**User Story:** 
https://github.com/ita-social-projects/Car-Back-End/issues/32
