### ISSUE TITLE
[Settings] The "Car" app crashed after adding a photo when re-open the app.

### ISSUE THREAD

**Issue by Vladyslava95** [ita-social-projects/SoftServeCar-Back-End#316]
**Environment:**  Samsung Galaxy S10e, Android 10
**Reproducible:** rarely, for "Delete avatar" also
**Build found:** 1.0.85

**Preconditions**
The "Car" app is opened
The "My Profile" page is opened

**Steps to reproduce**
1. Go to the 'Setting' page
2. Long press the avatar icon
3. Press on the "Add avatar"
4. Upload avatar photo
5. Close the "Car" app
6. Re-open the "Car" app
7. Observe the result

**Actual result**
The "Car" app crashed after adding a photo when re-open the app.

**Expected result**
The "Car" app crashed  must re-open 

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

**Comment by Vladyslava95** [comment]
https://user-images.githubusercontent.com/71496479/110704747-12156380-81fe-11eb-8b75-a9beb6c4f95c.mp4

**Comment by SashaOsypova** [comment]
Isn't reproduced on Samsung Galaxy S8 and Samsung Galaxy S10e. Build 1.0.153
