### ISSUE TITLE
[Send Notifications] Send Push Notification

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/SoftServeCar-Back-End#321]
**As any** User **I want to** receive push notifications on my phone **so that** I could be informed that a new Message or Notification was sent to me.

**Description**
User shall have the possibility to receive push-notifications to the screen saver or when the application works in background mode.

### Acceptance Criteria
1.	User shall receive push-notification about the new Message or Notification when the application works in background mode.
2. The push-notification shall consist of:  App icon, sender N&S, the text of the message/notification.
3. User shall be transferred to the current Chat or Notification page by pressing the notification.
4. System shall differentiate Chat messages and Notification messages to transfer to the appropriate App screen.

**Epic link**
Epic #78 

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by nrevutska** [comment]
test comment
