### ISSUE TITLE
[Add a Car] Keyboard is not hide when edix box is closed

### ISSUE THREAD

**Issue by MarianKornaha** [ita-social-projects/SoftServeCar-Back-End#325]
**Environment:** Android 9.0, Asus ROG Phone 2
**Reproducible:** always
**Build found:** 1.0.88

**Preconditions**
1. Run Car app
2. Log in to account

**Steps to reproduce**
1. Go to 'My profile'
2. Click on 'Your Cars'
3. Click "Add a car"
4. Click on Brand\Model\Color
5. Choose "Manual input"
6. Close edit box

**Actual result**
The virtual keyboard is still displayed.

**Expected result**
The virtual keyboard closed

**User story and test case links**
E.g.: "User story #33 
![car11](https://user-images.githubusercontent.com/78917960/111439282-e0286380-870d-11eb-8d06-efbda88e0f37.jpg)
![car12](https://user-images.githubusercontent.com/78917960/111439285-e0c0fa00-870d-11eb-8092-83fff2918cb5.jpg)

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

**Comment by EdgeOfMordor** [comment]
Cannot reproduce
