### ISSUE TITLE
[Chats] Chat textbox appears when go back from journey chat

### ISSUE THREAD

**Issue by zxmiron** [ita-social-projects/SoftServeCar-Back-End#327]
**Environment:** Android 9, Samsung SM-A530F, Nexus 5 (appetize.io simulator);
**Reproducible:** always on OS Android 9
**Build found:** 1.0.89

**Preconditions**
Use device with OS Android 9

**Steps to reproduce**
1. Go to 'Chats' homepage
2. Tap on any chat
3. Tap on 'Back' button in the left top corner OR hard 'Back' button

**Actual result**
Opens 'Chats' homepage and shortly appears chat textbox in the bottom of page

![Screenshot_20210317-131000_Car](https://user-images.githubusercontent.com/78938450/111458769-81b9b000-8722-11eb-93f6-3879ebe14900.jpg)

https://user-images.githubusercontent.com/78938450/111458771-82524680-8722-11eb-97d6-d909238376a5.mp4

**Expected result**
Opens 'Chats' homepage

**Comments**
Bug doesn't reproduce on Android 10, 11, iOS 12, 13, 14

**User story and test case links**
User story #22

**Comment by Aleks-1914** [comment]
Bug is fixed
