### ISSUE TITLE
[Chat]Alert "No internet connection" is not shown at the participants chats when the Internet connection is lost.

### ISSUE THREAD

**Issue by Vladyslava95** [ita-social-projects/SoftServeCar-Back-End#332]
**Reproducible:** always
**Build found:** 1.0.91

**Preconditions**
The "Car" app is opened
The Chat page is opened

**Steps to reproduce**
1. Go to the participant's chat.
2. Turn off the Internet connection
3. Observe the result.

**Actual result**
Alert "No internet connection" is not shown on the participant's chats when the Internet connection is lost.

**Expected result**
Alert "No internet connection" is shown on the participant's chats, when the Internet connection is lost.

**Comment by Vladyslava95** [comment]
https://user-images.githubusercontent.com/71496479/111695404-bd946880-883b-11eb-9985-601386ca1312.mp4

**Comment by AnnaBalah** [comment]
Is also reproducible for following **Environment:** Redmi Note 9 Pro, Android 12.0.3, app version 1.0.140
**User Story:** https://github.com/ita-social-projects/Car-Back-End/issues/45

**Comment by YuriiDanyliv** [comment]
ita-social-projects/Car-Front-End#418

**Comment by RuslanPleskun** [comment]
Bug fixed.
