### ISSUE TITLE
[Preferences] Alert "No internet connection" is not shown when the Internet connection is lost.

### ISSUE THREAD

**Issue by Vladyslava95** [ita-social-projects/SoftServeCar-Back-End#333]
**Reproducible:** always
**Build found:** 1.0.91

**Preconditions**
The "Car" app is opened
The "My Profile" page is opened

**Steps to reproduce**
1. Go to the "Preferences" page.
2. Turn off the Internet connection
3. Observe the result.

**Actual result**
Alert "No internet connection" is not shown when the Internet connection is lost.

**Expected result**
Alert "No internet connection" is shown when the Internet connection is lost.

**Comment by Vladyslava95** [comment]
https://user-images.githubusercontent.com/71496479/111702600-33e99880-8845-11eb-81cd-481aebbba3d2.mp4

**Comment by SashaOsypova** [comment]
Is reproduced on Samsung Galaxy S10e and Samsung Galaxy A51. Build 1.0.153

**Comment by YuriiDanyliv** [comment]
ita-social-projects/Car-Front-End#418

**Comment by RuslanPleskun** [comment]
Bug fixed.
