### ISSUE TITLE
[Manage Address Book] New address cannot be added

### ISSUE THREAD

**Issue by AnnaBalah** [ita-social-projects/SoftServeCar-Back-End#349]
**Environment:** Android 12.0.2, app version 1.0.99, Redmi Note 9 Pro
**Reproducible:** always
**Build found:** commit https://github.com/ita-social-projects/Car-Front-End/commit/47bb53bb30c7d189a518a316131bf5177353b513

**Preconditions**

**Steps to reproduce**
1. Go to 'My Profile'
2. Click on ‘Address book’
3. Choose ‘Add new Address'

**Actual result**
Map is not displayed. Field ’Address’ is disabled and dropdown format is incorrect (but you can type in the input field).

![image](https://user-images.githubusercontent.com/81674765/113268250-db53da00-92df-11eb-9731-e2955cfdc7e4.png)

**Expected result**
Map is displayed, address can be typed and dropdown is displayed correctly (as on mockup)

![image](https://user-images.githubusercontent.com/81674765/113268363-f7577b80-92df-11eb-9682-e278d8e7f8f0.png)

**User story and test case links**
User Story #44 

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

**Comment by AnnaBalah** [comment]
Not a bug, as his option is not implemented yet.

**Comment by yuliya-polyuganych** [comment]
Can not reproduce
