### ISSUE TITLE
[Chat] The "Load more" button is present if  more than 50 messages.

### ISSUE THREAD

**Issue by Vladyslava95** [ita-social-projects/SoftServeCar-Back-End#353]
**Reproducible:** always
**Build found:** 1.0.99

**Preconditions**
The "Car" app is opened
The user is a participant of the Journey
The chat is created

**Steps to reproduce**
1. Go to the "Chat" page
2. Go to journey chat 
3. Scroll up the journey chat
4. Observe the result

**Actual result**
The "Load more" button is present if more than 50 messages.

**Expected result**
The oldest message must be shown when the user scrolls up without a button.
E.g.: "User story #45 
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

**Comment by Vladyslava95** [comment]
![Load more](https://user-images.githubusercontent.com/71496479/113341043-5abfc880-9335-11eb-8c8d-761f0cc39de1.jpg)

**Comment by AnnaBalah** [comment]
Is also reproducible for following **Environment:** Redmi Note 9 Pro, Android 12.0.3, app version 1.0.140
