### ISSUE TITLE
[Search for a journey] The status "Requested" is shown after refresh the page

### ISSUE THREAD

**Issue by Vladyslava95** [ita-social-projects/SoftServeCar-Back-End#354]
**Reproducible:** always
**Build found:** 1.0.99

**Preconditions**
The car app is opened
The user is logged in

**Steps to reproduce**
1. Go to the 'Search for a journey' page 
2. Tap on a journey
3. Tap  the "REQUEST TO DRIVER" button
4. Tap the "Confirm" button
5. Press "OK" on the pop-up window
6. Observe the result

**Actual result**
The status of the journey is "Request to Driver" after clicking on the "Confirm" button.

**Expected result**
The status of the journey must be "Requested" after clicking on the "Confirm" button.

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

**Comment by Vladyslava95** [comment]
https://user-images.githubusercontent.com/71496479/113343275-4c26e080-9338-11eb-9562-a0f73c0f6450.mp4

**Comment by AnnaBalah** [comment]
Was tested for following **Environment:** Redmi Note 9 Pro, Android 12.0.3, app version 1.0.143

**User Story:** https://github.com/ita-social-projects/Car-Back-End/issues/14

**Comment by Aleks-1914** [comment]
The bug is not reproduced anymore
