### ISSUE TITLE
[Search for a Journey] The status of journey disappears after clean data.

### ISSUE THREAD

**Issue by Vladyslava95** [ita-social-projects/SoftServeCar-Back-End#359]
**Reproducible:** always, rarely, sometimes etc.
**Build found:** 1.0.99

**Preconditions**
The "Car" app is opened
The user is logged in
The "Journey" status is "Requested"

**Steps to reproduce**
1. Clean data and cash
2. Log into the app
3. Go to the "Search for a journey page"
4. Select requested journey
5. Observe the result

**Actual result**
The status of the journey disappears after clean data.

**Expected result**
The status of the journey is not changing after clean data.

**User story and test case links**
User Story #44, #16

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

**Comment by SashaOsypova** [comment]
Not a bug
