### ISSUE TITLE
[Edit Profile] Wrong alignment "EDIT PROFILE" title

### ISSUE THREAD

**Issue by MarianKornaha** [ita-social-projects/SoftServeCar-Back-End#364]
**Environment:** Asus ROG Phone 2, OnePlus 7
**Reproducible:** always
**Build found:** 1.0.168

**Preconditions**
Run Car application

**Steps to reproduce**
EDIT PROFILE:
1. Go to 'My Profile'.
2. Click on 'Settings'.
3. Click on the big button with name\surname.
4. Pay attention to the "EDIT PROFILE" label.

REQUEST A RIDE:
1. Go to 'Ride' page.
2. Click on 'SEARCH A RIDE'.
3. Set 'From' address field with correct value (e.g. "Warsaw Chopin Airport, Żwirki i Wigury, Warsaw, Poland").
4. Set 'To' address field with correct value (e. g. "Chornovola 67zh, Lviv, Lviv Oblast, Ukraine").
5. Set 'Departure time' field with correct value (e.g. 23.05; Sun; 12:33)
6. Click on 'SEARCH' button.
7. Click on 'Request'.
8. Pay attention to the "MORE OPTIONS" label.

MORE OPTIONS:
1. Go to 'Ride' page.
2. Click on any ride that you have.
3. Click on Ellipsis menu "...".
4. Pay attention to the "REQUEST A RIDE" label.

**Actual result**
"EDIT PROFILE", "REQUEST A RIDE" and "MORE OPTIONS" labels have a wrong alignment.

**Expected result**
All elements have a right alignment.

**User story and test case links**
https://github.com/ita-social-projects/Car-Back-End/issues/32

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")
![image](https://user-images.githubusercontent.com/78917960/113667973-3c055d00-96ba-11eb-8d27-3cdc1f1d7ee0.png)

![image](https://user-images.githubusercontent.com/82941067/119120525-0e3f6200-ba35-11eb-9a36-0e2fd4c3531e.png)

![image](https://user-images.githubusercontent.com/82941067/119120550-14354300-ba35-11eb-8100-1122e0aa3258.png)

**Comment by EdgeOfMordor** [comment]
Not a bug

**Comment by RuslanPleskun** [comment]
The bug is still present.
Environment: OnePlus 7
Reproducible: always
Build found: 1.0.150

**Comment by RuslanPleskun** [comment]
![Edit_photo_alignment](https://user-images.githubusercontent.com/82941067/117860980-938a8000-b299-11eb-9e15-36d62e65cb6e.jpg)
