### ISSUE TITLE
[Chats] Incorrect timestamp of sent message 

### ISSUE THREAD

**Issue by zxmiron** [ita-social-projects/SoftServeCar-Back-End#365]
**Environment**: iOS (appetize simulator)
**Reproducible**: always
**Build found**: 1.0.100

**Preconditions**
1. App is opened and logged in.
2. User shall be joined to at least 1 journey 

**Steps to reproduce**
1. Go to Chats homepage
2. Tap on any chat
3. Write any message and send it
4. Verify the timestamp of sent message
5. Tap on 'Back' button and tap again on the same chat
6. Verify the timestamp of sent message

**Actual result**
Step **4** - timestamp is 1 hour less
![image](https://user-images.githubusercontent.com/78938450/113886258-35194000-97c9-11eb-89a6-f11c6cbcac00.png)

Step **6** - timestamp is 3 hours less
![image](https://user-images.githubusercontent.com/78938450/113886599-7c9fcc00-97c9-11eb-8a99-0f0c7d1e2054.png)

**Expected result**
Timestamp should be actual

**User story and test case links**
User story #45

**Comment by volodymyrRuban1** [comment]
Fixed https://github.com/ita-social-projects/Car-Front-End/pull/590
