### ISSUE TITLE
[Chats, Journeys] Incorrect timestamp of journey's start

### ISSUE THREAD

**Issue by zxmiron** [ita-social-projects/SoftServeCar-Back-End#366]
**Environment**: Android, iOS (appetize simulator)
**Reproducible**: always
**Build found**: 1.0.100

**Preconditions**
1. App is opened and logged in.
2. User shall be joined to at least 1 journey 

**Steps to reproduce**
1. Go to Chats homepage
2. Verify the timestamp of journey's start
3. Go to Journey homepage
4. Tap on the same journey
5. Verify the timestamp of journey's start

**Actual result**
**Step 2**: Android - timestamp is correct, iOS - timestamp is 3 hours less
![Screenshot_20210407-175737_Car+](https://user-images.githubusercontent.com/78938450/113892482-b3c4ac00-97ce-11eb-900d-f97599a53e36.jpg)
![iphone8_14 1-03+](https://user-images.githubusercontent.com/78938450/113892706-f4bcc080-97ce-11eb-8cdc-b9339a85fa0b.png)

**Step 5**: Android, iOS - timestamp is 3 hours less
![Screenshot_20210407-175748_Car+](https://user-images.githubusercontent.com/78938450/113893161-6d238180-97cf-11eb-9160-dcc61e850611.jpg)
![iphone8_14 1-04+](https://user-images.githubusercontent.com/78938450/113893189-74e32600-97cf-11eb-9d54-2b05323a515d.png)

**Expected result**
Timestamp should be correct

**User story and test case links**
User story #4 , #22

**Comment by volodymyrRuban1** [comment]
Fixed https://github.com/ita-social-projects/Car-Front-End/pull/590
