### ISSUE TITLE
[Manage journey] 'Message all' button and its background aren't aligned vertically

### ISSUE THREAD

**Issue by zxmiron** [ita-social-projects/SoftServeCar-Back-End#372]
**Environment:** iOS 14.1 iPhone 8 (appetize simulator), Android 9 Redmi Note 5, Android 9 SM-A530F
**Reproducible:** always
**Build found:** 1.0.100

**Preconditions**
1. App is opened and logged in.
2. User shall be joined to at least 1 journey

**Steps to reproduce**
1. Go to Journey homepage
2. Scroll down to the list of journeys which you are added to
3. Tap on any journey
4. Scroll down the list of passengers and verify alignment of 'Message all' button

**Actual result**
'Message all' button and its background aren't aligned vertically - there is a whole below them, scrolled list of passengers is visible in it 
OR 
'Message all' button and its background are partially hidden behind footer menu.
Alignment depends on whether navigation buttons are present on the screen. 

iOS 14.1 iPhone 8 (appetize simulator):
https://user-images.githubusercontent.com/78938450/114503894-abd59380-9c36-11eb-9b2a-336290b45441.mp4

Android 9 Redmi Note 5:
![image](https://user-images.githubusercontent.com/78938450/114352787-ee369c00-9b74-11eb-8188-09f07859e9af.png)

Android 9 SM-A530F:
_navigation buttons are ON_
![image](https://user-images.githubusercontent.com/78938450/114504299-551c8980-9c37-11eb-98ae-31629121c20f.png)
_navigation buttons are OFF_
![image](https://user-images.githubusercontent.com/78938450/114504634-d70cb280-9c37-11eb-9d5f-2de150a75041.png)

**Expected result**
'Message all' button and its background should be aligned vertically correctly

**User story and test case links**
User story #4

**Comment by vovazavislyak** [comment]
Tip for developers: this depends on whether there are navigation buttons on the screen. You need to align the button vertically, depending on whether they are present and their height.

**Comment by AnnaBalah** [comment]
Was retested on Android 12.0.2, Redmi Note 9 Pro, app version 1.0.124 and issue is still reproducible. 

<img width="137" alt="US_12_Journey_Search_1" src="https://user-images.githubusercontent.com/81674765/115628117-c976bd00-a308-11eb-9286-34d388102a00.png">

**Comment by RuslanPleskun** [comment]
Bug fixed.
