### ISSUE TITLE
[Search for Journey] Keyboard overlaps "Comments" input 

### ISSUE THREAD

**Issue by AnnaBalah** [ita-social-projects/SoftServeCar-Back-End#373]
**Environment:** Android 12.0.2, app version 1.0.99, Redmi Note 9 Pro
**Reproducible:** always
**Build found:** https://github.com/ita-social-projects/Car-Front-End/commit/5e12dcae8cb2ec853b7e7d800b506d68c88f9c36

**Preconditions**
GPS is enabled on this device, permission is granted for this app

**Steps to reproduce**
1. Go to 'Search for Ride'
2. Click on 'OK' to go to "Search Result" page
3. Choose ride from the list
4. Click on 'Send Request'
5. Press on 'Comments' input

**Actual result**
Keyboard overlaps 'Comments' input and all bottom menu.

<img width="137" alt="US_12_Journey_Search_1" src="https://user-images.githubusercontent.com/81674765/114854131-2c3df500-9ded-11eb-928f-174c546349e0.png">

**Expected result**
When keyboard appears, comments section is displayed above keyboard as well as all other information from this menu.

**Postconditions**

**User story and test case links**
User story #14 

**Labels to be added**
"Bug" ("bug"), Priority ("pri:medium")

**Comment by bohatyrov** [comment]
KeyboardAvoidingView doesn't work properly inside BottomPopup.
react-native-keyboard-height forces component to re-render.
