### ISSUE TITLE
[Manage Car Info] Car is still avaliable in the list after removing it

### ISSUE THREAD

**Issue by Tarasll** [ita-social-projects/SoftServeCar-Back-End#388]
**Environment:** Redmi 4a.

**Reproducible:** always.

**Build found:** v.1.0.135

**Preconditions**
1. User is log in
2. "My Cars" page isopened

**Steps to reproduce**
1. Click on any car
2. Click on "Remove" button
3. Click on "Yes, delete it" button

**Actual result**
App redirects to "My Cars" page  but car is still avaliable in the list

**Expected result**
System shall delete all information about chosen car

**User story and test case links**
E.g.: "User story #53 

**Labels to be added**
"Bug" ("bug"), Priority ("pri:medium")

**Comment by AnnaBalah** [comment]
This feature is not implemented yet.
