### ISSUE TITLE
[Manage Car Info] When user go to "Your Car" page info about a car is reseted

### ISSUE THREAD

**Issue by Tarasll** [ita-social-projects/SoftServeCar-Back-End#389]
**Environment:** Redmi 4A.
**Reproducible:** always.
**Build found:** v.1.0.135

**Preconditions**
1. User is logged in
2. "My Cars" page is opened
3. Car is added

**Steps to reproduce**
1. Click on any car
2. Look at all information about a car

**Actual result**
All information is reseted

**Expected result**
Fields: "Brand", "Model", "Color", "Plate number" must be filled with data

**User story and test case links**
E.g.: "User story #53 

**Labels to be added**
"Bug" ("bug"), Priority ("pri:medium
![555](https://user-images.githubusercontent.com/81674722/116037666-19d77d00-a671-11eb-8d20-d558d7e3b704.png)
")

**Comment by AnnaBalah** [comment]
This feature is not implemented yet.
