### ISSUE TITLE
[Manage journey] Schedule a Ride

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/SoftServeCar-Back-End#392]
**As a** User (Driver) **I want to** have the option of rides scheduling  **so that** I avoid the need to input regular rides each time.

**Description**
This option is needed for regular rides which take place on the same days of the week.

**Mockup**
<img width="446" alt="US_392_Schedule_Ride" src="https://user-images.githubusercontent.com/62544149/116237693-3951d100-a769-11eb-8202-124669e25590.png">

### Acceptance Criteria
1. User accesses the page through More Options menu (US[#58](https://github.com/ita-social-projects/Car-Front-End/issues/58)) and Select routebpage (US[#24 ).
2. User shall choose from boxes with "day of the week" names.
3. IF User chooses "Repeat every workday" option by pushing on the mark box, the system shall mark all weekdays (except Saturday and Sunday) in the DB.
4. IF User pushes the "Save" button, the system shall save User's choice into DB.

#### Assumptions & Constraints
1. At Ride homepage (US[#245 ) User shall see a list of scheduled ride only for the next 14 days.
2. "Save" button shall be disabled if User didn't make any changes.

**Epic link**
Epic #70 

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by ivanstrilchuk** [comment]
Acceptance criteria 1(about ride scheduling page access) should be updated.
Should be added acceptance criteria about checkbox in 'SCHEDULE A RIDE'.
