### ISSUE TITLE
[Chats] The chat header and 'Back' button disappear after tapping on the input field

### ISSUE THREAD

**Issue by RuslanPleskun** [ita-social-projects/SoftServeCar-Back-End#424]
**Environment:** Android 11.0.0.2, OnePlus 7
**Reproducible:** always
**Build found:** 1.0.150

**Preconditions**

1. App is opened and logged in.
2. User is joined to at least 1 journey.

**Steps to reproduce**

1. Choose 'ALL' rides.
2. Tap on any ride.
3. Click on 'MESSAGE TO ALL' button.
4. Tap on input field.

**Actual result**
The chat header and 'Back' button disappear after tapping on the input field.

**Expected result**
The chat header and 'Back' button is present at the top of the screen after tapping on the input field.

**User story and test case links**
User story #45

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

![Top_of_the_chat](https://user-images.githubusercontent.com/82941067/117870684-1b29bc00-b2a5-11eb-8999-bbc811556e6d.png)

https://user-images.githubusercontent.com/82941067/117870777-3a284e00-b2a5-11eb-8781-0dd85d408976.mp4

**Comment by Aleks-1914** [comment]
Bug is not reproduced on v.1.0.285 - fixed
