### ISSUE TITLE
[Journeys, Models, Notifications] HTTPGet method returns incorrect status code when data is received from the server

### ISSUE THREAD

**Issue by RuslanPleskun** [ita-social-projects/SoftServeCar-Back-End#428]
**Reproducible:** always.

**Preconditions**
1. Set HTTP method as GET.

**Steps to reproduce**
1. Set the following values in the URL field (each of them separately and in turn):
    - https://car-project.azurewebsites.net/api/journeys/past/40 (Journey)
    - https://car-project.azurewebsites.net/api/journeys/upcoming/40 (Journey)
    - https://car-project.azurewebsites.net/api/journeys/scheduled/44 (Journey)
    - https://car-project.azurewebsites.net/api/journeys/recent/56 (Journey)
    - https://car-project.azurewebsites.net/api/models/by-brand/64 (Model)
    - https://car-project.azurewebsites.net/api/Notification/notifications/25 (Notification)
2. Click on the 'Send' button.

**Actual result**
Method HTTPGet returns status code "200 OK".

**Expected result**
Method HTTPGet shall return status code "204 No Content" because such IDs do not exist in the DB.

**User story and test case links**
User story #4 #14 #130 #33 

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

![image](https://user-images.githubusercontent.com/82941067/117962119-8ae08b00-b327-11eb-821d-20bdc8c91f66.png)

**Comment by YuriiDanyliv** [comment]
Will not be implemented.
