### ISSUE TITLE
[Add a ride] Missalingment in a "Choose a Car" dropdown menu

### ISSUE THREAD

**Issue by Tarasll** [ita-social-projects/SoftServeCar-Back-End#430]
**Environment:** Redmi 4A, Android.
**Reproducible:** always.
**Build found:** v1.0.153

**Preconditions**

**Steps to reproduce**
1. Go to "Add a ride"
2. Choose addresses
3. Look at "Choose a Car" dropdown

**Actual result**
Missalingment in a "Choose a Car" dropdown.

**Expected result**
borders must be integral.

**Postconditions**

**User story and test case links**

**Labels to be added**
"Bug" ("bug"), Priority ("pri:low ")
![photo_2021-05-12_09-26-22](https://user-images.githubusercontent.com/81674722/117928365-23fdaa80-b304-11eb-89e2-fb52ddf4a7c3.jpg)

**Comment by ivanstrilchuk** [comment]
Environment: Samsung GALAXY  A71, Android 11
Reproducible: always.
Build found: v1.0.153

Steps to reproduce

Go to "Add a ride"
Choose addresses
Look at "Choose a Car" dropdown
Actual result
Missalingment in a "Choose a Car" dropdown. (shot below)

Expected result
borders must be integral.
![add s ride m1](https://user-images.githubusercontent.com/87978779/130879702-a70a3865-a331-43bf-ab3a-1825350a423c.jpg)


Labels to be added
"Bug" ("bug"), Priority ("pri:low ")
