### ISSUE TITLE
[Settings] Options list for Profile photo is empty after User interupts adding a photo process

### ISSUE THREAD

**Issue by AnnaBalah** [ita-social-projects/SoftServeCar-Back-End#437]
**Environment:** Redmi Note 9 Pro, android 10, app version 1.0.153
**Reproducible:** always
**Build found:** https://github.com/ita-social-projects/Car-Front-End/commit/8d13acac2c48631c23165a223d3cd4f646f19a03

**Preconditions**
Delete Profile photo, if you have one.

**Steps to reproduce**
1. Go to 'Settings' page
2. Click on button with photo details and choose 'Add photo'
3. Click 'Cross' (X) in order to return on 'Settings' page
4. Click on button with photo details once more

**Actual result**
When interrupting adding a photo process, 'Add photo' menu is blank.

https://user-images.githubusercontent.com/81674765/118088883-6bea0380-b3d0-11eb-87fa-5125cf817a1b.mp4

**Expected result**
After interrupting adding a photo process, 'Add photo' menu is present and button can be pushed.

**User story and test case links**
User story #32

**Comment by Aleks-1914** [comment]
The bug is not reproduced anymore
