### ISSUE TITLE
[Journey] Journey is not deleted after using DELETE request

### ISSUE THREAD

**Issue by RuslanPleskun** [ita-social-projects/SoftServeCar-Back-End#510]
**Reproducible:** always.

**Preconditions**
Postman is opened.
New request is added.
DELETE method is set.

**Steps to reproduce**
1. Set the following link into the request URL field: https://car-api-project.azurewebsites.net/api/journeys/155
2. Click on 'Send' button.

**Actual result**
Journey with Id 155 is not deleted after using DELETE request and status code "401 Unauthorized" received.

**Expected result**
Journey with any existing Id should be deleted after using DELETE request and status code "200 OK" with information about deleted journey should appear.

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

![image](https://user-images.githubusercontent.com/82941067/120096640-50ebf300-c135-11eb-8a6c-6110ca1eb545.png)

![image](https://user-images.githubusercontent.com/82941067/120096658-6eb95800-c135-11eb-847e-2f93b3fa4e2b.png)

**Comment by vovazavislyak** [comment]
Not a bug
