### ISSUE TITLE
[Chats page] Inconsistency of Journey's start time

### ISSUE THREAD

**Issue by IrynkaVandzhala** [ita-social-projects/SoftServeCar-Back-End#516]
**Environment:** Mi 9 Lite MIUI Global 12.0.7 Android 10
**Reproducible:** always
**Build found:** 1.0.185

**Preconditions**
User is logged in.
Car app is opened.
Ride is created and MESSAGE TO ALL is sent.

**Steps to reproduce**
1. Go to Ride page
2. Verify the timestamp of journey's start
3. Tap on Chats page
4. Verify the timestamp of journey's start

**Actual result**

1. Incorrect time appearance of Journey's start on the Chats page (3 hours less)

**Expected result**

1. Journey's start time on the Chats page is the same as on the Ride page
![image](https://user-images.githubusercontent.com/84583510/120290155-bf15ee80-c2ca-11eb-8f2f-1d36c219feaf.png)

User story and test case links
E.g.: "User story #376

Labels to be added
"Bug" ("bug"), Priority ("pri: ")

**Comment by roman-pankiv** [comment]
fixed with ita-social-projects/Car-Front-End/pull/432
