### ISSUE TITLE
[Settings Page] UI doesn't correspond mock-up

### ISSUE THREAD

**Issue by Gege-Hrom** [ita-social-projects/SoftServeCar-Back-End#529]
Environment: MI 8 Lite, Android version 10 QKQ1. 190910. 002.

Reproducible: always.
Build found: 1.0.181

Preconditions:
User is logged in.
Car app is opened.

Steps to reproduce:
1. Tap on 'My Profile' icon on menu
2. Tap on 'Settings'
3. Tap on user window several times in a row
4. Pay attention at the shadowing background 

Actual result
User window isn't shadowed.
Sliding option menu 'Edit profile' doesn't disappear by tapping on the shadowed background.
The background starts blinking.
https://user-images.githubusercontent.com/84737624/120754329-317a0f00-c515-11eb-8e5c-b29b2ee970b9.mp4

Expected result
User window is shadowed.
Sliding option menu 'Edit profile' disappears by tapping on the shadowed background.
<img width="218" alt="Screenshot 2021-06-04 at 09 18 24" src="https://user-images.githubusercontent.com/84737624/120754834-db599b80-c515-11eb-8533-6f32251a42c1.png">

User story and test case links
User Story  #32 

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

**Comment by AndriiDzendzia** [comment]
Can’t reproduce

**Comment by Aleks-1914** [comment]
The bug is fixed and isn't reproduced in v.1.0.282
