### ISSUE TITLE
[Send Notifications] View Stop

### ISSUE THREAD

**Issue by kvashch** [ita-social-projects/SoftServeCar-Back-End#532]
**As a** User (Driver) **I want to** have the possibility to view Pick up stops in previously created ride **so that** I can take aware of all stops of the ride.

**Mockup** 
<img width="362" alt="US_532_View_Stop" src="https://user-images.githubusercontent.com/62544149/139029533-221f1592-fed4-413b-b26f-3327d6dd8f56.png">
https://www.figma.com/file/q2QTrUQLmisr90FzvU7HLm/Request-Mockup?node-id=3733%3A11463

### Acceptance Criteria
1. User accesses "View stops" from New applicant page US(#5 ). 
2. System shall let user to choose desired stop by clicking on the desired location. 
3. Pick up stops shall be chosen by system automatically based on the closest distance from the stops indicated in the search request.  
5. WHEN user push Accept button, system shall send request approvement notification to the passenger US(#416) 

**Epic link**
E.g.: Epic #78 

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by vladzavorotny** [comment]
Assumptions & Constraints maybe to remove
