### ISSUE TITLE
[Settings page] Scrolling panel doesn't open correctly after error message appears

### ISSUE THREAD

**Issue by SashaOsypova** [ita-social-projects/SoftServeCar-Back-End#540]
**Environment:** Samsung Galaxy S10e, Samsung One Plus 8 Pro
**Reproducible:** always
**Build found:** v1.0.102

**Preconditions**
1. Open the app
2. Go to 'My profile'-> 'Settings'
3. Photo isn't chosen

**Steps to reproduce**
1. Click big button with the details
2. Click 'Add photo' option
3. Choose a photo
4. Click 'Retry' button on the error message pop-up window
5. Click 'Add photo' option
6. Observe the result

**Actual result**
1. Scrolling panel appears without 'Edit photo'/ 'Add photo' option  

**Expected result**
1. 'Add photo' option appears at the bottom of the scrolling panel 

**User story and test case links**
User story #32

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

https://user-images.githubusercontent.com/82940100/121173587-a7f27600-c861-11eb-961d-d830cb041a5c.mp4

**Comment by nrevutska** [comment]
cannot reproduce
