### ISSUE TITLE
[Request to Driver] The From/To icons are displayed like stops on the "Ride" page for the creator of ride.

### ISSUE THREAD

**Issue by Roman-Mytsko** [ita-social-projects/SoftServeCar-Back-End#544]
Environment: Android 12.0.1, Xiaomi Mi 8.
Reproducible: always.
Build found: v1.0.206

Preconditions:
1. Geolocation is enabled.
2. Internet connection is available.
3. The user is authorized.
4. App is opened.
5. Ride is created: From="Arena Lviv, Stryiska Street, Lviv"; To="Lviv Railway Station, Dvirtseva Square, Lviv"; Fee="FREE"; Departure time: "29.11;Mon;11:47".
6. "Search for Ride" page is opened.

Steps to reproduce:
1. Fill all mandatory fields by data:
From="Arena Lviv, Stryiska Street, Lviv"; To="Lviv Railway Station, Dvirtseva Square, Lviv"; Fee="FREE"; Departure time: "29.11;Mon;11:47".
2. Tap on "SEARCH" button.
3. Tap on presented journey box.
4. Swap down the panel with Request to driver details.
5. Pay attention to the From/To icons.

Actual result:
The From/To icons are displayed like stop point on the "Ride" page.

Expected result:
The "From" point has an icon which symbolizes the beginning of the ride for the creator of the trip.
The "To" point has an icon which symbolizes the end of the ride for the creator of the trip.

User story and test case links:
User story #14 

![From,To points](https://user-images.githubusercontent.com/82975806/121356779-dcd1fc00-c939-11eb-8622-2c50fae717f1.jpg)
![Start point](https://user-images.githubusercontent.com/82975806/121356793-dfccec80-c939-11eb-872e-e45a76ee4a72.jpg)
![Final point](https://user-images.githubusercontent.com/82975806/121356803-e2c7dd00-c939-11eb-8d8f-77233054634b.jpg)

**Comment by RuslanPleskun** [comment]
Bug fixed.
