### ISSUE TITLE
[Settings] User can't log out from application after 1st attempt

### ISSUE THREAD

**Issue by Gege-Hrom** [ita-social-projects/SoftServeCar-Back-End#556]
Environment: Mi 8 Lite  Android 10.
https://user-images.githubusercontent.com/84737624/122337418-fc26e580-cf46-11eb-8bf9-
Reproducible: always
Build found: #217: Commit 91fe134 

Preconditions
User Logged in 

Steps to reproduce
1. Go to 'My profile' -> 'Settings'
2. Tap on 'Logout' in the right upper corner
3. Tap 'Yes, log out' button
Actual result
After logout tapped and confirmed user remains logged in and 'Ride' screen displayed

https://user-images.githubusercontent.com/84737624/122337418-fc26e580-cf46-11eb-8bf9-1413198c6b6e.mp4

Expected result
Login screen should be displayed after user taps logout 

User story and test case links
User story #32
[Test case](https://jira.softserve.academy/browse/CAR-163)

**Labels to be added**
"Bug" ("bug"), Priority ("pri: medium")

**Comment by YuriiDanyliv** [comment]
not reproduced

**Comment by ivanstrilchuk** [comment]
Environment: Nexus5 Android 8.1
Reproducible: always
Build: Build Android and iOS #254

Preconditions:
- User Logged in

Steps to reproduce:
- Go to 'My profile' -> 'Settings'
- Tap on 'Logout' in the right upper corner
- Tap 'Yes, log out' button

Actual result:
- After logout tapped and confirmed user remains logged in and 'Ride' screen displayed

Expected result:
- User is logged out from 1-st attempt

Attempts to repeat: 7

**Comment by Aleks-1914** [comment]
The bug is reproducing (not always)

https://user-images.githubusercontent.com/87984409/129313381-228f2cd3-7181-4aa3-b9b9-c34ef5190b19.mp4

**Comment by Aleks-1914** [comment]
Not fixed yet

**Comment by Aleks-1914** [comment]
The bug is not reproduced anhymore
