### ISSUE TITLE
[Add a Ride] After Ride creation Ride Type and Fee do not match the selected option

### ISSUE THREAD

**Issue by IrynkaVandzhala** [ita-social-projects/SoftServeCar-Back-End#564]
Environment: Xiaomi Mi 9 Lite, Android 10, MIUI 12 12.0.6.0
Reproducible: always
Build found: v1.0.228.apk

Preconditions:

Internet connection is available
The user is authorized
App is opened
"Add a Ride" page is opened

Steps to reproduce:
1. Select From/To/Departure time
2. Select Ride Type as OWN CAR
3. Select Fee as FREE
4. Click on Publish
5. Go to created Ride
6. Observe the Result

Actual result:

1. The Ride is created
2. Ride Type is shown as Taxi
3. Fee is shown as Paid

https://user-images.githubusercontent.com/84583510/123126343-facb5080-d451-11eb-8a3b-df96e15e1d60.mp4

Expected result:

1. The Ride is created
2. Ride Type is shown as Own Car
3. Fee is shown as Free

User story and test case links
User story #403 

Labels to be added
"Bug" ("bug"), "Priority" ("pri: ")[](url)

**Comment by Aleks-1914** [comment]
Same defect was appeared again while other fixed defect was retested.

**Comment by vladzavorotny** [comment]
I can't reproduce.
