### ISSUE TITLE
[Send Notifications] User (Passenger) has not received notification Request Approvement from a Driver

### ISSUE THREAD

**Issue by IrynkaVandzhala** [ita-social-projects/SoftServeCar-Back-End#571]
Environment: Xiaomi Mi 9 Lite, Android 10, MIUI 12 12.0.6.0
Reproducible: always
Build found: v1.0.233.apk

Preconditions

The app is opened
The driver has created a Ride (e.g. Lviv Airport - Forum Lviv, 01.07, 23:17)

Steps to reproduce:

1. User (Passenger) is logged in
2. Search for Ride page is opened
3. Select From/To/Departure time (same as Drivers Ride (e.g. Lviv Airport - Forum Lviv, 01.07, 23:17))
4. Click Search
5. Select Ride and click Send Request->Confirm->Ok
6. Log in to the Drivers account
7. Go to the Notifications -> New Applicant page
8. Click Accept
9. Log in to the User (Passenger) account
10. Observe the Result

Actual result:

1. User (Passenger) has not received notification Request Approvement

![image](https://user-images.githubusercontent.com/84583510/123704941-ee3e6200-d86e-11eb-8186-dcaf9885b303.png)

Expected result:

1. User (Passenger) received notification Request Approvement
![image](https://user-images.githubusercontent.com/84583510/123704606-7e2fdc00-d86e-11eb-9db6-0dbeb94d3831.png)

User story and test case links
User story #5 

Labels to be added
"Bug" ("bug"), "Priority" ("pri: ")

**Comment by vladzavorotny** [comment]
Closed with ita-social-projects/Car-Front-End/pull/519

**Comment by Aleks-1914** [comment]
The bug is fixed in ver.1.0.282
