### ISSUE TITLE
[Manage User Profile] The initial letters of the user's name and surname in cyrillic aren't displayed in the user icon when the user hasn't added a profile photo

### ISSUE THREAD

**Issue by Gege-Hrom** [ita-social-projects/SoftServeCar-Back-End#574]
**Environment:** Mi 8 Lite Android 10.
**Reproducible:** always.
**Build found:** Build Android and iOS #231: Commit 85fb6ee

**Preconditions**
A user is registered in Cyrillic.
A user is logged into the application.

**Steps to reproduce**
1. Tap "My Profile" tab on the footer
2. Pay attention to the user icon on a Profile page
**Actual result**
There is no initial letters in the user's icon. User icon is empty. 
![IMAGE 2021-06-29 23:26:39](https://user-images.githubusercontent.com/84737624/123862789-75eca500-d931-11eb-90b0-9ce1eb5a8621.jpg)

**Expected result**
The initial letters of the user's name and surname should be displayed in the user icon when the user hasn't added a profile photo.

![IMAGE 2021-06-29 23:28:19](https://user-images.githubusercontent.com/84737624/123863052-c237e500-d931-11eb-9949-56c60bbba546.jpg)

**User story and test case links**
E.g.: "User story #18

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

**Comment by YuriiDanyliv** [comment]
this user had a filled image ID field in the database
