### ISSUE TITLE
[Send Notification] Passenger received incorrect Notification about Ride cancellation

### ISSUE THREAD

**Issue by IrynkaVandzhala** [ita-social-projects/SoftServeCar-Back-End#590]
Environment: Xiaomi Mi 9 Lite, Android 10, MIUI 12 12.0.6.0
Reproducible: always
Build found: v1.0.238.apk

Preconditions

Car app is opened
Ride is created
Passenger is added into the Ride

Steps to reproduce

1. Log in as a Driver
2. Go to created Ride
3. Tap on ellipsis menu-> 'More Optionts' pop-up is opened
4. Tap on 'Edit ride details'->Departure time->Change date->Apply changes->Apply->Ok
5. Repeat step 3
6. Tap on 'Edit ride details'->'Cancel ride'->Yes, cancel it->Ok
7. Log in as a Passenger
8. Go to 'Notification' tab
9. Observe the result

Actual result

1. Notification "Ride details have been updated" was received
2. Click "Ride details have been updated"->View->App is not responding (screen becomes white)

https://user-images.githubusercontent.com/84583510/124571438-7238b100-de50-11eb-8c9f-4d21ac01b438.mp4

Expected result

1. Notification "Ride is canceled" was received
2. Tap notification "Ride is canceled"-> pop-up window 'Ride is canceled' appears

User story and test case links
User Story #265 

Labels to be added
"Bug", Priority ("pri:").

**Comment by Aleks-1914** [comment]
![Canselation message](https://user-images.githubusercontent.com/87984409/129139456-a09e4a23-6743-41cb-a443-23076ba01d0f.jpg)
Now this bug fixed but the screen that is opened instead of white screen is  wrong. Another bug report is created #618
