### ISSUE TITLE
[Ride request] User (driver) doesn't get User's (passenger) ride request 

### ISSUE THREAD

**Issue by Aleks-1914** [ita-social-projects/SoftServeCar-Back-End#667]
**Environment:** Xiaomi Mi Redmi Note 8 Pro, Android 10, MIUI 12 12.0.8.0
**Reproducible:** always
**Build found:** v1.0.297.apk

**Preconditions**
Car app is opened
Ride is created
Ride Request is successfully created with same parameters: From/To/Departure time/Fee(All)

**Steps to reproduce**
Log in as a Driver
Tap on the 'Notification' tab

**Actual result**
No notification about the Passenger's ride request in notification list.

**Expected result**
The notification about the Passenger's ride request in notification list.

"User story #100
[Test case](https://jira.softserve.academy/browse/100)"

"Bug" ("bug"), Priority ("pri: ")
![изображение_viber_2021-09-02_09-05-59-669](https://user-images.githubusercontent.com/87984409/131791035-fe42fd8a-8b67-495a-8af6-78555daa2a45.jpg)
![изображение_viber_2021-09-02_09-05-59-727](https://user-images.githubusercontent.com/87984409/131791056-1ff1003e-d81d-4050-ac30-bd8221614b6a.jpg)
![изображение_viber_2021-09-02_09-05-59-838](https://user-images.githubusercontent.com/87984409/131791069-f017bd12-aedf-49f8-9aa0-6e62e775b4d8.jpg)
![изображение_viber_2021-09-02_09-05-59-868](https://user-images.githubusercontent.com/87984409/131791091-c083aa47-6bbe-4a80-a71b-8585c162f21e.jpg)
![изображение_viber_2021-09-02_09-05-59-957](https://user-images.githubusercontent.com/87984409/131791101-dce7da2c-7d2f-4787-8c2d-c5f89c21be13.jpg)

**Comment by vladzavorotny** [comment]
Not a bug
