### ISSUE TITLE
[Add a ride] "Kyiv-Odessa" route isn't build

### ISSUE THREAD

**Issue by VikaUrzan** [ita-social-projects/SoftServeCar-Back-End#686]
**Environment:** Xiaomi MiA1, Android 9
**Reproducible:** sometimes
**Build found:** v1.0.303

**Preconditions**
"Car" is opened

**Steps to reproduce**
1. Go to 'Add to ride'
2. Click on 'From' field.
3. Enter 'Kyiv'.
4. Click on 'To' field.
5. Enter 'Odessa'.
6. Double click 'Confirm' button.

**Actual result**

1. Route isn't built.
2. App show error message.

**Expected result**
Route is built

"Bug" ("bug"), Priority ("pri: medium")

https://user-images.githubusercontent.com/67322591/132326693-8d574464-5faa-4a46-a048-da5715b8603b.mp4

**Comment by vladzavorotny** [comment]
Cannot reproduce
Some of the routes GoogleMaps cannot build

**Comment by VikaUrzan** [comment]
Bug reproduce if quickly double tap "Confirm" button

**Comment by vladzavorotny** [comment]
won't fix
