### ISSUE TITLE
[Manage User's Profile Settings] Change App Mode

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/SoftServeCar-Back-End#689]
**As any** User **I want to** adjust the App mode**so that** making the App screen is easier on my eyes.

Mockup
![image](https://user-images.githubusercontent.com/95188061/152444964-79e8e64a-4d3c-4e3b-a0f5-f5265ef71ed4.png)
https://www.figma.com/file/q2QTrUQLmisr90FzvU7HLm/Request-Mockup?node-id=7245%3A23209
### Acceptance Criteria
1. User accesses the "Mode options" at the page "My Profile" US #18.
2. When the User taps the "Dark option", the system should switch on dark mode.
3. When the User pushes the "Light option", the system should switch off dark mode and back to the light theme. 
4. When the User chooses the option "AS A SYSTEM", the screen mode of the App will be automatically adjusted to the  Device theme. 

**Epic link**
Epic #64  

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by Vlas2001** [comment]
Implemented menu
Hidden, waiting for final requirements
