### ISSUE TITLE
[Ride] App is crashed after cancelling past journey

### ISSUE THREAD

**Issue by VikaUrzan** [ita-social-projects/SoftServeCar-Back-End#698]
**Environment:** Xiaomi MiA1, Android 9.
**Reproducible:** always.
**Build found:** v1.0.309.

**Steps to reproduce**
1. App is opened.
2. Choose Past journey.
2. Click the more option.
3. Click "Cancel ride".
4. Confirm cancellation.
5. Open next past ride.

**Actual result**
The app is crashed.

**Expected result**
The app is worked.

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

https://user-images.githubusercontent.com/67322591/133207072-aa449bd5-a766-4198-916a-62ca5bb86ac6.mp4

**Comment by volodymyrRuban1** [comment]
Cannot reproduce
