### ISSUE TITLE
[Notifications] Incorrect link names for the departure point are displayed when receiving notification that request was approved by Driver

### ISSUE THREAD

**Issue by YanaRudyi** [ita-social-projects/SoftServeCar-Back-End#707]
**Environment:** OnePlus 8 Pro, Android 11
**Reproducible:** Always
**Build found:** 1.0.317

**Preconditions**

1. The "Car" app is opened.
2. Log in as Passenger.
3. Have a request which was accepted.

**Steps to reproduce**

1. Go to the 'Notification' tab
2. Click on request.

**Actual result**
Only the "Start" and "Stop" links near the departure point of passengers are displayed.

**Expected result**
A link with a specific departure point for passengers is displayed.

**User story and test case links**
E.g.: "User story #416

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")
![2021-09-16 09 15 59](https://user-images.githubusercontent.com/89380889/133569501-ffcb052e-d78d-45ec-a510-6841e62817df.jpg)

**Comment by vladzavorotny** [comment]
Fix works only with newly created rides.
