### ISSUE TITLE
[Ride Homepage] A user can create or book another journey when the user has already created or booked a journey with the same time

### ISSUE THREAD

**Issue by YanaRudyi** [ita-social-projects/SoftServeCar-Back-End#714]
**Environment:** OnePlus 8 Pro, Android 11
**Reproducible:** Always
**Build found:** 1.0.317

**Preconditions**
1. Open app.
2. Login as a driver

**Steps to reproduce**
1. Click "Add a ride"
2. Fill in 'From' and 'To' fields (e.g. 'From' = 'Lviv National Academic Opera and Ballet Theatre named after Solomiya Krushelnytska', 'To' = 'Kyiv, Ukraine')
3. Click 'Confirm' button.
4. Fill in another field with correct data (e.g. 'Departure time' = '22.10l Wed; 16:30', Ride Type = 'Taxi', Fee = 'Free', Available seats = '4'
5. Click on 'Publish' button
6. Click "Add a Ride"
7. Create a new trip with the same data as in the previous trip (e.g. 'From' = 'Lviv National Academic Opera and Ballet Theatre named after Solomiya Krushelnytska', 'To' = 'Kyiv, Ukraine')

**Actual result**
The second ride is added.

**Expected result**
Error message.

**Labels to be added**
"Bug" ("bug"), Priority ("pri: Low")

**Comment by volodymyrRuban1** [comment]
Can't reproduce

**Comment by volodymyrRuban1** [comment]
Add journey time restriction #769
