### ISSUE TITLE
[Notification] User does not receive push notifications when a ride is created on request

### ISSUE THREAD

**Issue by YanaRudyi** [ita-social-projects/SoftServeCar-Back-End#715]
**Environment:** OnePlus 8 Pro, Android 11
**Reproducible:** Always
**Build found:** 1.0.332

**Preconditions**

1. Open the app.
2. Login as a passager.
3. Create a ride request.

**Steps to reproduce**
1. Login as a driver. 
2. Create a ride according to the previously created request.

**Actual result**
Passenger does not receive push notifications regarding the creation of a trip on request.

**Expected result**
The passenger receives push notifications regarding the creation of a trip on request.

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

**Comment by Vlas2001** [comment]
Fixed in previous pull request
