### ISSUE TITLE
[Search Results] Journey with updated route doesn't show

### ISSUE THREAD

**Issue by VikaUrzan** [ita-social-projects/SoftServeCar-Back-End#718]
**Environment:** Xiaomi MiA1, Android 9
**Reproducible:** sometimes
**Build found:** v1.0.334
**Preconditions**

1. New journey is created (e.g. From: Lviv, To: Kyiv, Departure Time:  24.09, 00:28, Fee: Paid, Ride Type: Taxi).
2. Search this journey as a passenger.
3. Journey is shown.

**Steps to reproduce**
1. Update this journey (e.g To: Poltava, First Stop: Rivne, Second Stop: Zhytomyr)
2. Search this journey as a passenger.

**Actual result**
Journey with updated route isn't shown

**Expected result**
Journey with updated route is shown

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")
<img width="358" alt="Screenshot 2021-09-23 at 00 28 02" src="https://user-images.githubusercontent.com/67322591/134429681-448aec4f-5111-4024-bbbc-31fdf3467abe.png">
![photo5357146810797372647](https://user-images.githubusercontent.com/67322591/134430711-c482513b-182b-46ff-8e37-53dc5c8a4e46.jpg)
![photo5357146810797372651](https://user-images.githubusercontent.com/67322591/134430720-e41aecfb-4150-4cd6-bd38-c77d5187e073.jpg)
![photo5357146810797372652](https://user-images.githubusercontent.com/67322591/134430724-a79bdb3d-a087-4480-bd0d-1335b9794a58.jpg)

**Comment by Vlas2001** [comment]
Fixed in previous pull request
