### ISSUE TITLE
[Ride Homepage] List of agreed trips has a different implementation when opening 'Ride' page

### ISSUE THREAD

**Issue by YanaRudyi** [ita-social-projects/SoftServeCar-Back-End#722]
**Environment:** OnePlus 8 Pro, Android 11 and iPhone 12, iSO 15
**Reproducible:** Always
**Build found:** 1.0.334

**Preconditions**
1. Car app is opened.
2. Log in as a user

**Steps to reproduce**
1. Go to 'Ride' page

**Actual result**
The list of agreed trips (toggle buttons) is displayed as outlined buttons, and if the toggle button is active, it has a black highlight in a light theme.

**Expected result**
The list of agreed trips (toggle buttons) has no outline. If the toggle button is active, it has an outline below the name button in a light theme.

**User story and test case links**
 User story #23 
[Test case](https://jira.softserve.academy/browse/100)"
<img width="958" alt="image" src="https://user-images.githubusercontent.com/89380889/134477102-90c3aebd-75d8-441a-a27d-8236cf16eab2.png">

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

**Comment by volodymyrRuban1** [comment]
Fixed https://github.com/ita-social-projects/Car-Front-End/pull/598
