### ISSUE TITLE
[Search Results] Rout built incorrect after updating journey

### ISSUE THREAD

**Issue by VikaUrzan** [ita-social-projects/SoftServeCar-Back-End#729]
**Environment:** Google Pixel 2, Android 8
**Reproducible:** sometimes
**Build found:** v.1.0.339

**Preconditions**

1. Open "Car" app.
2. Log in.

**Steps to reproduce**
1. Create a new journey (e.g. From: Lviv, To: Kyiv, Departure time: 25.09 15:10).
2. Update this journey (e.g. From: Poltava, To: Kyiv, Stop: Rivne, Stop: Zhytomyr)

**Actual result**
Route built incorrect.

**Expected result**
Rout built correct.

**User story and test case links**
E.g.: "User story #44 

**Labels to be added**
"Bug" ("bug"), Priority ("pri: low ")

![image](https://user-images.githubusercontent.com/67322591/134675581-f3b69fcc-0470-476d-b396-d46fd62622f5.png)

**Comment by vladzavorotny** [comment]
doesn't reproduce
