### ISSUE TITLE
[API, Log in] User creates new user with invalid email when logging in via 'Postman'

### ISSUE THREAD

**Issue by YanaRudyi** [ita-social-projects/SoftServeCar-Back-End#737]
**Environment:** Postman
**Reproducible:** Always

**Preconditions**
1. Postman is opened.

**Steps to reproduce**
1. Select 'POST' method 
2. Set 'https://car-api-project.azurewebsites.net/api/login'
3. Set request body with incorrect email (e.g.
'{
  "name": "Yana",
  "surname": "Rudyi",
  "email": "rudayana@ry"
}')
4. Click on 'Send' button
5. Go to 'Car' DB
6. Open 'User' table
7. Check that the user is created

**Actual result**
New user created.

**Expected result**
400 Bad Request Status.

**Labels to be added**
"Bug" ("bug"), Priority ("pri: High")

**Comment by AndriiDzendzia** [comment]
Closed with #809 #810
