### ISSUE TITLE
[Withdrawal Notification] Withdrawal notification does not display the 'Start' and 'Finish' points correctly when passenger decided to withdraw a ride

### ISSUE THREAD

**Issue by YanaRudyi** [ita-social-projects/SoftServeCar-Back-End#739]
**Environment:** OnePlus 8 Pro, Android 11
**Reproducible:** Always
**Build found:** 1.0.344

**Preconditions**
1. Open the app.
2. Login as a driver.
3. The driver has a rejected ride.

**Steps to reproduce**
1. Go to 'Notification' tab
2. Click on 'Withdrawal' notification.

**Actual result**
'Start' and 'Finish' points are displayed as 'User name Start' and 'User name Finish'

**Expected result**
'Start' and 'Finish' points are displayed start point (e.g 'Opera House) and finish point (e.g. 'Ternopil, Ternopil Oblast, Ukraine) 

**User story and test case links**
E.g.: "User story #459 
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

![2021-09-29 11 39 55](https://user-images.githubusercontent.com/89380889/135234631-c2cf1c7c-d6f0-4924-973a-e81ccf39721f.jpg)

**Comment by vladzavorotny** [comment]
Fix works only with newly created rides.
