### ISSUE TITLE
[Notification] Driver doesn't see push notification about a new message from the invited passenger

### ISSUE THREAD

**Issue by VikaUrzan** [ita-social-projects/SoftServeCar-Back-End#743]
**Environment:** Google Pixel 2, Android 8
**Reproducible:** always
**Build found:** v1.0.350

**Preconditions**

1. Created a new journey.
2. Passenger accepted the invite.
3. Driver confirm invite.
4. A passenger sends a message through "Message all".

**Steps to reproduce**
1. Open app.
2. Log in as a driver.

**Actual result**
A push notification about a new message doesn't show.

**Expected result**
A push notification is shown.

**Comment by Nataliia-Kavaler** [comment]
Verified
