### ISSUE TITLE
[Chats] Message counter shows "0" by default.

### ISSUE THREAD

**Issue by ivanstrilchuk** [ita-social-projects/SoftServeCar-Back-End#748]
Environment: Samsung Galaxy S6 edge, Android 5
Reproducible: always.
Build found: v1.0.350 commit 9594201

Preconditions:

1. 'Car' application is opened
2. User is logged
3. 'Chats' window is opened

Steps to reproduce:
Verify that message counter disappears when there are no unread messages

Actual result:
Message counter Shows "0" when there are no unread messages

Expected result:
Message counter disappears when there are no unread messages

User Story #22 

![Message counter](https://user-images.githubusercontent.com/87978779/135583192-81e8b5ad-b20a-4f5e-b4c5-b7dc1e00b97a.jpg)

**Comment by Vlas2001** [comment]
Not reproduce
