### ISSUE TITLE
[Ride Details] Inability to edit fee in scheduled ride

### ISSUE THREAD

**Issue by Aleks-1914** [ita-social-projects/SoftServeCar-Back-End#760]
**Environment:** Xiaomi Mi Redmi Note 8 Pro, Android 11, MIUI 12.5.3
**Reproducible:** always
**Build found:** v1.0.353.apk

**Preconditions**
Car app is opened
Regular ride is created
User as a driver logged in the app
The 'Ride Details' of the regular ride is opened

**Steps to reproduce**
Change the 'Fee' from 'Free' value to 'Paid'
Tap 'OK' in the the 'Paid ride' pop up window
Tap 'Apply Changes' in the 'Ride Details' page
Tap Apply' in the 'CHANGES' pop up window

**Actual result**
There is an 'Error' pop up window with 'Ride update is failed' message on the screen

**Expected result**
The 'Fee' is change

https://user-images.githubusercontent.com/87984409/135977916-4ccfa40a-401e-4715-b316-088801d2ed16.mp4

d

**Comment by Sydir** [comment]
didn't fix
