### ISSUE TITLE
[Ride] Ellipsis menu doesn't work

### ISSUE THREAD

**Issue by VikaUrzan** [ita-social-projects/SoftServeCar-Back-End#781]
**Environment:** iPhone 12, iOS 15
**Reproducible:** always
**Build found:** v1.0.366

**Preconditions**
1. Open app.
2. Log in.

**Steps to reproduce**

1. Click on upcoming journey.
2. Click on the 'Ellipsis' menu.

**Actual result**
The "More options" menu doesn't work. 

**Expected result**
The "More options" menu works.

**User story and test case links**
User story #4 

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

https://user-images.githubusercontent.com/67322591/137304316-f6b3cea6-f543-4c7b-8dd1-f4c924c52d63.mp4

**Comment by volodymyrRuban1** [comment]
https://github.com/ita-social-projects/Car-Front-End/pull/632
