### ISSUE TITLE
[Ride invitation] Error message of 'New invitation' cant invite new user with valid email for a new ride  

### ISSUE THREAD

**Issue by Marta-Yasnuska** [ita-social-projects/SoftServeCar-Back-End#782]
Environment: Android Samsung Galaxy A 10s
Reproducible: always
Build found:v1.0.366.apk
Preconditions
1. Go to 'Add a ride'.
2. Choose some values for 'From' and 'To' in the text boxes
3. Press 'Confirm' button

Steps to reproduce
1. Go to 'Invited SoftServians' at the 'Ride details'.
2. Click on 'Add invitation'
3.  Type at the edit box some valid email.
4.  Pres on the information icon in edit box in which email was typed.

Actual result
Pop up the message 'There is no user with such an email' when you press on the information icon at the edit box. 

Expected result
User with a valid email must be successfully found and added to the invitation.

**Labels to be added**
"Bug" ("bug"), Priority ("pri:
![зображення_viber_2021-10-12_16-16-42-019](https://user-images.githubusercontent.com/91321998/137320392-5efafd3d-5b5f-4d7d-8aa9-78af09250504.jpg)

**Comment by Vlas2001** [comment]
Not reproduce
