### ISSUE TITLE
[Add a car] Failed error message after clicking on button 'Save' button to add a new car.

### ISSUE THREAD

**Issue by Marta-Yasnuska** [ita-social-projects/SoftServeCar-Back-End#783]
Environment: Android Samsung Galaxy A 10s
Reproducible: always
Build found:v1.0.366.apk

Preconditions:
1. Go to 'My profile' 
2. Open 'My cars'
3. Click on 'Add a car'

Steps to reproduce
1. Fill fields  'Brand', 'Model', 'Color' and plate number with some values.
2. Click on 'Save' button

Actual result
The error message 'Failed to add the car' appears. Return to 'My cars' menu and new car save anyway.

Expected result
After pushing 'Save' button on menu 'Add a car', car is saved and  'My cars' tab  is open.

![зображення_viber_2021-10-14_17-20-47-647](https://user-images.githubusercontent.com/91321998/137344370-390756e4-7813-4d85-b045-4c49d50ea62a.jpg)

"Bug" ("bug"), Priority ("pri: ")

**Comment by vladzavorotny** [comment]
Duplicate ita-social-projects/Car-Back-End/issues/774
