### ISSUE TITLE
[Login page] User can't log in with e-mail in the main 'Login page'

### ISSUE THREAD

**Issue by Marta-Yasnuska** [ita-social-projects/SoftServeCar-Back-End#791]
Environment: Android Samsung Galaxy A 10s
Reproducible: always
Build found: v1.0.371.apk

Preconditions

 Go to main 'Login page'

Steps to reproduce:

1. Type valid email address and press 'Login' button

Actual result
The system does not respond on the 'Login page'. Rotating action waiting icon. 

Expected result
The user logged into the system

Labels to be added
"Bug" ("bug"), Priority ("critical: ")

https://user-images.githubusercontent.com/91321998/137958704-72830ad3-c0b7-48f4-8f65-090a014513ee.mp4

**Comment by AndriiDzendzia** [comment]
Closed with #809 #810
