### ISSUE TITLE
[Ride Details] UI isn't matched with mock-up

### ISSUE THREAD

**Issue by VikaUrzan** [ita-social-projects/SoftServeCar-Back-End#794]
**Environment:** Google Pixel 2, Android 8
**Reproducible:** always
**Build found:** v1.0.372

**Preconditions**
1. Open app.
2. Log in.

**Steps to reproduce**
1. Go to 'Add a Ride'
2. Set data (e.g. From: Kyiv, To: Lviv). 
3. Click 'Confirm' button.

**Actual result**
'Ride Details' page isn't matched with mock-up

**Expected result**
https://www.figma.com/file/q2QTrUQLmisr90FzvU7HLm/Request-Mockup?node-id=3458%3A7934

**User story and test case links**
User story #3

**Labels to be added**
"Bug" ("bug"), Priority ("pri:low")
<img width="361" alt="Screenshot 2021-10-20 at 10 41 41" src="https://user-images.githubusercontent.com/67322591/138051288-1fcc6931-0851-4b00-bfce-43602d881258.png">

![image](https://user-images.githubusercontent.com/67322591/138051333-6373f0ae-469a-4fd1-880d-a14c41b1c84e.png)

**Comment by stasgut** [comment]
https://github.com/ita-social-projects/Car-Front-End/pull/643

**Comment by stasgut** [comment]
https://github.com/ita-social-projects/Car-Front-End/pull/654
