### ISSUE TITLE
[Preferences] 'Comments' edit box is empty by default 

### ISSUE THREAD

**Issue by VikaUrzan** [ita-social-projects/SoftServeCar-Back-End#798]
**Environment:** Xiaomi MiA1, Android 9
**Reproducible:** always
**Build found:** v1.0.377

**Preconditions**
1. Open app.
2. Log in.

**Steps to reproduce**
1. Go to 'My Profile'.
2. Click on 'Preferences'.

**Actual result**
'Comments' edit box is empty by default 

**Expected result**
'Comments' edit box has 'Input text' placeholder by default

**User story and test case links**
User story #21 

**Labels to be added**
"Bug" ("bug"), Priority ("pri: low")
![photo5443048690748077391](https://user-images.githubusercontent.com/67322591/138228183-0df49ab5-21af-45ef-b6ba-ed3722fa567d.jpg)
![image](https://user-images.githubusercontent.com/67322591/138228319-9a00af6d-a66e-4836-becc-6ea39c4cfda4.png)

**Comment by Sydir** [comment]
'Comments' edit box should  have 'Input text' placeholder by default not 'Write your comments'

**Comment by Sydir** [comment]
fixed in v1.0.408
