### ISSUE TITLE
[Ride Invitations] User can invite himself on his trip

### ISSUE THREAD

**Issue by VikaUrzan** [ita-social-projects/SoftServeCar-Back-End#817]
**Environment:** Google Pixel 2, Android 8
**Reproducible:** always
**Build found:** v1.0.383

**Preconditions**
1. Open app.
2. Log in.

**Steps to reproduce**
1. Go to 'Add a Ride'.
2. Set data (e.g. From: Kyiv, To: Lviv, Departure time: 25.10; Wed; 15:12, Ride Type: Taxi, Fee: Free).
3. Go to 'Invited SoftServians'.
4. Set the email of the current account.

**Actual result**
User can invite himself

**Expected result**
 Error message appears under field 'New invitation'
https://www.figma.com/file/q2QTrUQLmisr90FzvU7HLm/Request-Mockup?node-id=3734%3A12248

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

**Comment by Sydir** [comment]
wrong error message appears, should be 'Error' under field 'New invitation' like in mock-up.
