### ISSUE TITLE
[Manage Joiners] Create Ride Invitations

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/SoftServeCar-Back-End#822]
**As a** Driver **I want to** invite some colleagues to join the ride **so that** they participate in my ride.

**Description**
<img width="445" alt="US_822_Ride_Invitations" src="https://user-images.githubusercontent.com/62544149/139033415-64000187-ccad-44d1-b6b7-c7b014ec302d.png">
https://www.figma.com/file/q2QTrUQLmisr90FzvU7HLm/Request-Mockup?node-id=3733%3A11566
https://www.figma.com/file/q2QTrUQLmisr90FzvU7HLm/Request-Mockup?node-id=3734%3A12248
https://www.figma.com/file/q2QTrUQLmisr90FzvU7HLm/Request-Mockup?node-id=3734%3A12071
![UML State_Machine_Invite_User](https://user-images.githubusercontent.com/62544149/144829750-4c2cf3f6-73a3-4abe-beb0-eb706694c513.jpg)

### Acceptance Criteria
1. User accesses to this screen from Publish a Ride page (US[#58](https://github.com/ita-social-projects/Car-Front-End/issues/58)) or Edit the Ride page (US[#9 ].
2. User shall input SS e-mail address into the edit box.
2.1. IF User inputs an invalid e-mail address and the system didn't find it in SSBS and between registered App users, the system shall mark the edit box with a red line and write "Error" under it.
2.1.1. Add invitation button shall be disabled.
2.2. User shall input only a unique SS email.
2.2.1. If User inputs the same SS email more than once, the system shall mark the edit box with a red line and write "Error" under it. 
3. WHEN User pushes Add Invitation button, the system shall send a notification to the invited User.
4. User shall see a list of e-mails addresses (where invitations were sent) with the statement for each invitation (Sent, Accepted, Declined).
5. WHEN User pushes Save button, system shall save data into DB and transfer User to ___.

### Assumptions & Constraints
1. Quantity of invited Users shall not exceed the number of available seats for this ride.
1.1. IF any invited User rejects the invitation, the inviting person can send invitation to another App User.

**Epic link**
Epic #68 

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by nrevutska** [comment]
Implemented
