### ISSUE TITLE
[Ride Details] UI isn't matched with mock-up

### ISSUE THREAD

**Issue by VikaUrzan** [ita-social-projects/SoftServeCar-Back-End#831]
**Environment:** Google Pixel 2, Android 8
**Reproducible:** always
**Build found:** v1.0.387

**Preconditions**
1. Open app.
2. Log in.

**Steps to reproduce**
1. Go to 'Add a Ride'.
2. Set data (e.g From: Kyiv, To: Lytovka).
3. Click the ellipsis menu.
4. Add Stop (e.g. Via: Rivne).
5. Click the 'Confirm' button.

**Actual result**
1. Incorrect indents between fields.
2. Incorrect name of page.
3. Incorrect labels.

**Expected result**
https://www.figma.com/file/q2QTrUQLmisr90FzvU7HLm/Request-Mockup?node-id=4193%3A16173

**Labels to be added**
"Bug" ("bug"), Priority ("pri: low")
<img width="384" alt="Screenshot 2021-10-29 at 14 02 55" src="https://user-images.githubusercontent.com/67322591/139426480-56138ba2-7365-4bdc-b972-7e24fb1f81f3.png">
<img width="384" alt="Screenshot 2021-10-29 at 14 11 14" src="https://user-images.githubusercontent.com/67322591/139426488-b3bc3c69-5cf1-4da8-a214-16babf2c6351.png">

![image](https://user-images.githubusercontent.com/67322591/139426556-c5c277f0-fc60-446e-b803-bcac7786e711.png)

**Comment by stasgut** [comment]
https://github.com/ita-social-projects/Car-Front-End/pull/662

**Comment by VikaUrzan** [comment]
The arrow icon is absent near Invited Softservians (Xiaomi MiA1, Android 9)
![Screenshot_20211105-154509](https://user-images.githubusercontent.com/67322591/140525444-46e1c44b-9065-456c-b0a4-17e2014dc80f.png)

**Comment by stasgut** [comment]
https://github.com/ita-social-projects/Car-Front-End/pull/675

**Comment by Sydir** [comment]
not all is corrected
![image](https://user-images.githubusercontent.com/91271776/140658848-9313ab29-4545-4869-83a3-e8032fec031b.png)

![image](https://user-images.githubusercontent.com/91271776/140658869-3a596aa7-242d-495e-83e6-8da441556d91.png)

**Comment by Sydir** [comment]
1. page title should be 'Publish a Ride'
2.  Should be distance between departure time and stop

![incor title and distance](https://user-images.githubusercontent.com/91271776/142981665-85c6023f-9bdb-4592-adc4-86f5ff54089e.jpg)

**Comment by Sydir** [comment]
Incorrect color of 'point' icons in disabled edit boxes

![incor points](https://user-images.githubusercontent.com/91271776/143659666-e720cfb9-67d9-4df8-8478-29c255c24672.jpg)
