### ISSUE TITLE
[Global] Fields have incorrect width of borders

### ISSUE THREAD

**Issue by VikaUrzan** [ita-social-projects/SoftServeCar-Back-End#833]
**Environment:** All
**Reproducible:** always
**Build found:** v1.0.387

**Actual result**
All fields have incorrect width of borders

**Expected result**
<img width="357" alt="Screenshot 2021-10-29 at 09 33 26" src="https://user-images.githubusercontent.com/67322591/139431262-f78d60ec-1b53-42dd-bd15-7c006f33efe8.png">

![image](https://user-images.githubusercontent.com/67322591/139430333-be226b96-4c68-4961-970a-dda4171e371c.png)
![image](https://user-images.githubusercontent.com/67322591/139430480-7c5898a2-681f-4455-a525-e25abf39143c.png)

**Comment by Nataliia-Kavaler** [comment]
Verified
