### ISSUE TITLE
[Ride] Error message is appeared when driver in created own ride want to message all passenger 

### ISSUE THREAD

**Issue by Marta-Yasnuska** [ita-social-projects/SoftServeCar-Back-End#836]
Environment: all (IOS, Android) 
Reproducible: always
Build found: v1.0.388

Preconditions:
1. 'Car' app is open
2. User is logged
3. Main page is open

Steps to reproduce:
1. Go to 'Ride' menu
2. Click on 'All' rides
3. Tap on created ride
4. Tap on 'Message to all' button.

Actual result:
1. Error message pop up 'Ups, something went wrong' is appeared

Expected result:
1. User can type some text at text box by 'Message to all' option

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")
<img width="257" alt="2021-10-27 20-48-28 High Res Screenshot" src="https://user-images.githubusercontent.com/91321998/139462224-30ffb126-e03b-4a4d-8cd5-d48199a35aea.png">

**Comment by vladzavorotny** [comment]
Does the bug reproduce with the newly created rides(journeys)?

**Comment by Sydir** [comment]
the same situation
