### ISSUE TITLE
[Preferences] The new comment doesn't save and the counter below shows an incorrect number of symbols to enter after leaving the 'Preferences' page

### ISSUE THREAD

**Issue by Sydir** [ita-social-projects/SoftServeCar-Back-End#837]
**Environment:** Android 10, Samsung A7.
**Reproducible:** always
**Build found:** v1.0.388

**Preconditions**
The 'Car' is opened, the user is logged in, preferences are fulfilled
**Steps to reproduce**
1. Go to 'My Profile'
2. Click on 'Preferences'
3. Change 'Comments' (e. g. hi!)
4. Tap 'Back'
5. Tap 'Preferences'

**Actual result**
The new comment doesn't save and the counter below shows an incorrect number of symbols to enter after leaving the 'Preferences' page.

**Expected result**
The new comment saves and the counter below shows a number of symbols to enter after leaving the 'Preferences' page

 User story #21

**Labels to be added**
"Bug" ("bug"), Priority ("pri:high ")

https://user-images.githubusercontent.com/91271776/139473476-b1759b36-caef-45ec-a5ef-8afb4979d246.mp4

**Comment by Hennadii-Sapryka** [comment]
resolved #799

**Comment by Sydir** [comment]
counter shows an incorrect number of symbols

![image](https://user-images.githubusercontent.com/91271776/140572496-4768a6c1-b3bf-404d-954e-54af77fbb2da.png)

**Comment by Sydir** [comment]
fixed in v1.0.413
