### ISSUE TITLE
[Edit  Address] Ellipses menu is displayed in the right top corner of the page

### ISSUE THREAD

**Issue by Sydir** [ita-social-projects/SoftServeCar-Back-End#844]
**Environment:** Android 10, Samsung A7.
**Reproducible:** always.
**Build found:** v1.0.388

**Preconditions**
Log in to the 'Car' application and at least one address is added to 'Address Book' (e.g. Дім, Address: вул. Пасчна, Lviv, Lviv Oblast, Ukraine).

**Steps to reproduce**

1. Tap 'My Profile'
2. Tap 'Address Book'
3. Tap 'Домівка'

**Actual result**
 Ellipses menu is displayed in the right top corner of the page

**Expected result**
'Remove' is displayed in the right top corner of the page

User story #303 

**Labels to be added**
"Bug" ("bug"), Priority ("pri: low")
![ellipses menu in edit ride](https://user-images.githubusercontent.com/91271776/139925035-c9cb830f-01c7-4cf1-a602-f18c27723f69.png)

!['remove' mock-up in edit address](https://user-images.githubusercontent.com/91271776/139925058-070736a3-2ba0-4eef-b413-3ff6488607d8.png)

**Comment by Sydir** [comment]
The same situation

**Comment by Sydir** [comment]
'Remove' is smaller than  'Back'

![image](https://user-images.githubusercontent.com/91271776/140700132-f7d61aaa-010d-4967-bd18-eb258b5dd617.png)

**Comment by RomanKuts** [comment]
The bug has already been fixed 
![Знімок екрана 2021-12-29 123439](https://user-images.githubusercontent.com/81972015/147654408-e557d617-5357-4612-b2d0-1f11b9f8e6d0.jpg)
