### ISSUE TITLE
[Global] All borders must became red color when error message is appears

### ISSUE THREAD

**Issue by Marta-Yasnuska** [ita-social-projects/SoftServeCar-Back-End#846]
Environment: Android Samsung Galaxy A 10s
Reproducible: always
Build found: v1.0.388

Actual result:
After the error message appears, all borders should change color from black to red.

Expected result:
<img width="96" alt="зображення_viber_2021-11-03_12-47-34-943" src="https://user-images.githubusercontent.com/91321998/140048247-d2f1ac0e-884e-4c63-9877-ce489023d271.png">

**Comment by Sydir** [comment]
fixed v1.0.408
