### ISSUE TITLE
[Add a Car] The 'Save' button turns enable after typing only spaces in 'Brand' and 'Model' edit boxes.

### ISSUE THREAD

**Issue by Sydir** [ita-social-projects/SoftServeCar-Back-End#853]
**Environment:**  Android 10, Samsung A7.
**Reproducible:** always.
**Build found:** v1.0.395

**Preconditions**
The user is logged in to the 'Car'

**Steps to reproduce**
1. Tap My Profile' 
2. Tap 'My cars'
3. Tap 'Add a Car'
4. Type at least one space in 'Brand' and 'Model'
5. Select 'Color'

**Actual result**
The 'Save' button turns enable after typing only spaces in 'Brand' and 'Model' edit boxes.

**Expected result**
The 'Save' button should be disabled after typing only spaces in 'Brand' and 'Model' edit boxes.

User story #33 

**Labels to be added**
"Bug" ("bug"), Priority ("pri: "medium)

https://user-images.githubusercontent.com/91271776/140523741-5c271122-802d-4c0e-8d1c-688a3baa50c7.mp4

**Comment by Sydir** [comment]
the same situation

**Comment by Sydir** [comment]
fixed in v1.0.418

**Comment by Hennadii-Sapryka** [comment]
pull request #687

**Comment by Nataliia-Kavaler** [comment]
Verified
