### ISSUE TITLE
[Settings] App is crashed after log out

### ISSUE THREAD

**Issue by VikaUrzan** [ita-social-projects/SoftServeCar-Back-End#855]
**Environment:** Google Pixel 2, Android 8
**Reproducible:** always
**Build found:** 1.0.397

**Preconditions**
1. Open app.
2. Log in.

**Steps to reproduce**
1. Go to 'My Profile' page.
2. Click on 'Settings'
3. Click the 'Log out' button.
4. Click the 'Yes, log out' button. 

**Actual result**
The app is crashed after clicking the 'Yes, log out' button.

**Expected result**
The user is redirected to the main page.

**Labels to be added**
"Bug" ("bug"), Priority ("pri: critical")

https://user-images.githubusercontent.com/67322591/140524334-ce06db26-d98e-4676-a86e-d06bfb3a2497.mov

**Comment by RomanKuts** [comment]
The same account. Log out works correctl

https://user-images.githubusercontent.com/81972015/141136289-11dbe7c9-4a47-48ce-9d67-962a63508bb0.mp4
