### ISSUE TITLE
[Edit Car Info] The car is not deleted after canceling a ride with it.

### ISSUE THREAD

**Issue by Sydir** [ita-social-projects/SoftServeCar-Back-End#859]
**Environment:** Android 10, Samsung A7.
**Reproducible:** always.
**Build found:** v1.0.408

**Preconditions**
The user is logged in to the 'Car', car (e.g. Ford, Focus, Grey) is in 'My Cars' list and is added to the ride (e.g. Lviv-Kyiv, 10.11, 12:00). The ride is canceled.

**Steps to reproduce**
1. Go to 'My Profile'
2. Tap 'My Cars'
3. Choose a car (e.g. Ford Focus)
4. Tap 'Remove'
5. Tap 'Yes, delete it'

**Actual result**
The car is not deleted after canceling a ride with it.

**Expected result**
The car is deleted after canceling a ride with it.

User story #53 

**Labels to be added**
"Bug" ("bug"), Priority ("pri: medium")

![error to remove a car after cancel ride](https://user-images.githubusercontent.com/91271776/140658452-1a545862-5515-4841-9d29-61466aa6aad3.jpg)

**Comment by RomanKuts** [comment]
The right behavior. The car cannot be removed for two weeks after the cancellation or completion of the trip.
