### ISSUE TITLE
[Publish a Ride] 'Publish a Ride' UI doesn't match with mock-up.

### ISSUE THREAD

**Issue by Sydir** [ita-social-projects/SoftServeCar-Back-End#878]
**Environment:**  Android 10, Samsung A7.
**Reproducible:** always.
**Build found:** v1.0.425

**Preconditions**
The user is logged in to the 'Car'

**Steps to reproduce**
1. Go to 'Add A Ride'
2. Select 'From' and 'To' edit boxes (e.g. Lviv-Kyiv)
3. Tap 'Confirm'
4. Scroll down to the bottom of page

**Actual result**
'Publish a Ride' UI doesn't match with mock-up.

**Expected result**
'Publish a Ride' UI matches with mock-up.

User story https://github.com/ita-social-projects/Car-Front-End/issues/58

**Labels to be added**
"Bug" ("bug"), Priority ("pri: low ")

![publish button](https://user-images.githubusercontent.com/91271776/141830789-1a24c61a-66fe-434b-8fb4-b4d7a4c62b46.jpg)

mock- up

![image](https://user-images.githubusercontent.com/91271776/141831300-9b9b5d44-ffb8-48f0-9022-5d558e85d17b.png)

**Comment by Nataliia-Kavaler** [comment]
Verified
