### ISSUE TITLE
[Create ride request] 'Search a ride' page must be opened after choosing new filters in previously created ride

### ISSUE THREAD

**Issue by Marta-Yasnuska** [ita-social-projects/SoftServeCar-Back-End#881]
Environment: Android Samsung Galaxy A 10s
Reproducible: always
Build found: v1.0.428

Preconditions:
1. 'Car' app is open
2. User is logged
3. The main page is open

Steps to reproduce:
1. Go to 'Search for a ride' page
2. Put text on text fields:  'From' (e.g. Ternopil) press 'Confirm' button, 'To' (e.g. Krakow, Poland), and press the 'Confirm' button.
3. Scroll down to 'Departure time' and choose day and time (e.g. December 1, 14;45), press 'Done' button
4. Tap 'Search' button 
5. In 'Search result' page go to 'Request' on the right top corner on the page
6. In 'Request a ride' pop-up choose 'With new filters'
7. Tap the 'Yes, create' button at 'Are you sure' pop-up message

Actual result
The 'Create ride request' page is open

Expected result
 "Create a Ride Request" page is open with the Map view

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")
![зображення_viber_2021-11-17_13-32-14-697](https://user-images.githubusercontent.com/91321998/142193073-b9b0c027-a5b4-41c7-aa25-d7d6c027862d.jpg)

https://user-images.githubusercontent.com/91321998/142193096-3aad15dc-a53a-476e-9f25-024528a4237d.mov

**Comment by Nataliia-Kavaler** [comment]
Does not correspond to the mock-ups.

**Comment by Nataliia-Kavaler** [comment]
Verified
