### ISSUE TITLE
[Add a ride] Switcher doesn't work correctly in the dark theme at 'Schedule a ride' pop-up menu

### ISSUE THREAD

**Issue by Marta-Yasnuska** [ita-social-projects/SoftServeCar-Back-End#883]
Environment: Android Samsung Galaxy A 10s
Reproducible: always
Build found: v1.0.428

Preconditions:
1. 'Car' app is open
2. User is logged
3. The main page is open
4. The dark theme of the application is on

Steps to reproduce:
1. Go to 'Add a ride'
2. Click on ellipses menu at the right top corner of the window 
3. In 'More options' pop-up menu press on 'Schedule a ride'
4. Move 'Repeat every workday' switcher to the right.

Actual result:
'Repeat every workday' switcher doesn't work correctly.

Expected result:
'Repeat every workday' switcher must occupy the position in which it will be moved when pushing.

https://user-images.githubusercontent.com/91321998/142377682-03355ccd-de7e-49ff-9af6-7965013cfb37.mp4

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

**Comment by MedytskyiOleksandr** [comment]
Can`t reproduce
