### ISSUE TITLE
[Edit the Ride] 'Apply Changes' and 'Discard Changes' buttons place incorrect

### ISSUE THREAD

**Issue by Sydir** [ita-social-projects/SoftServeCar-Back-End#889]
**Environment:** Android 10, Samsung A7.
**Reproducible:** always.
**Build found:** v1.0.436.

**Preconditions**
Log to the app and create a ride (e.g. Krakow-Lviv, 26.11, 23:33). Open the main page.

**Steps to reproduce**
1. Go to previously created ride
2. Click on the ellipses menu
3. Click 'Edit Ride details'
4. Scroll down to the bottom of the page

**Actual result**
'Apply Changes' and 'Discard Changes' buttons place incorrect

**Expected result**
https://www.figma.com/file/q2QTrUQLmisr90FzvU7HLm/Request-Mockup?node-id=4139%3A15682

E.g.: "User story #9 

**Labels to be added**
"Bug" ("bug"), Priority ("pri: low ")

![edit ride_ incorrect button place](https://user-images.githubusercontent.com/91271776/143045041-2bb589b7-dae9-4680-8dfe-a7a581501139.jpg)

**Comment by RomanKuts** [comment]
The bug has already been fixed
![Знімок екрана 2021-12-29 154613](https://user-images.githubusercontent.com/81972015/147668716-abf3e481-35d3-4e04-825c-866666cc3ee0.jpg)
