### ISSUE TITLE
[Global] Day of the week is not displayed in the 'Departure time'.

### ISSUE THREAD

**Issue by Sydir** [ita-social-projects/SoftServeCar-Back-End#895]
**Environment:** Android 10, Samsung A7.
**Reproducible:** always.
**Build found:** v1.0.437.

**Actual result**
Day of the week is not displayed in the 'Departure time'.

**Expected result**
Day of the week should display in the 'Departure time'.

**Labels to be added**
"Bug" ("bug"), Priority ("pri: low ")

For example:

![day of week doesn't display](https://user-images.githubusercontent.com/91271776/143306455-48ed8aef-48e4-4852-a533-e98790510f32.jpg)

**Comment by Nataliia-Kavaler** [comment]
Verified
