### ISSUE TITLE
[Request to Driver] Driver's stops display when driver and passenger stops are the same.

### ISSUE THREAD

**Issue by Sydir** [ita-social-projects/SoftServeCar-Back-End#901]
**Environment:** Android 10, Samsung A7.
**Reproducible:** always.
**Build found:** v1.0.445.

**Preconditions**
The user as a driver is logged into the app and creates a ride (e.g.Chervonohrad - Zakopane, 29.11, 11:23 ). The user as a passenger is logged into the app and opens the homepage.

**Steps to reproduce**
1. Go to 'Find a Ride'
2. Select 'From' and 'To' edit boxes (e.g.Chervonohrad - Zakopane)
3. Select departure time (e.g. 29.11, 11:23)
4. Tap 'Search' button
5. Tap founded ride

**Actual result**
Driver's stops display when driver's and passenger's stops are the same.

**Expected result**
IF any of the driver's and passenger's locations are matched (stops are the same), the system shall show only Passenger's stop/stops.

User story #14 

**Labels to be added**
"Bug" ("bug"), Priority ("pri: medium ")

https://user-images.githubusercontent.com/91271776/143880099-e84f81b1-0123-4d87-a4ab-1932bee5db1e.mp4

**Comment by Nataliia-Kavaler** [comment]
Verified
