### ISSUE TITLE
[Map] Map doesn`t correspond to mock-up

### ISSUE THREAD

**Issue by MedytskyiOleksandr** [ita-social-projects/SoftServeCar-Back-End#905]
Environment: Android 10, Google Pixel 4.
Reproducible: always.
Build found: v1.0.437.

Preconditions
The user is logged to the 'Car' application and map is opened.

Steps to reproduce

Go to the 'Find a Ride' and press 'From'.

Actual result
Map doesn't correspond to the mock-up

Expected result
Map should be a lighter and correspond to the mock-up.

Labels to be added
"Bug" ("bug"), Priority ("pri:low ")
![msg358288331-67846](https://user-images.githubusercontent.com/92305676/144238614-d030488c-0ecd-4d2a-ba01-ac4efa22f6fd.jpg)
![Untitled1](https://user-images.githubusercontent.com/92305676/144238630-c46e7185-d873-4284-86d7-866ce3a83b58.png)

**Comment by Nataliia-Kavaler** [comment]
Verified
