### ISSUE TITLE
[Ride] Error message is appeared when user type some text for message to all in 'Ride' page

### ISSUE THREAD

**Issue by Marta-Yasnuska** [ita-social-projects/SoftServeCar-Back-End#906]
Environment: Android Samsung Galaxy A 10s
Reproducible: always
Build found: android.v.1.0.452

Preconditions:
1.'Car' app is open
2. The user is logged in
3. On app homepage go to 'Ride' menu

Steps to reproduce:
1. Go to 'All' rides
2. Click on 'Upcoming' and pick a ride
3. On the 'Ride' page of just picked ride press button 'Message all'
4. Type some text in textbox for message

Actual result:
When the user type some text in the textbox, the error message is appears

Expected result:
User can type and send message to other users

https://user-images.githubusercontent.com/91321998/144261300-91b03a26-d4af-4b5f-a03d-148bd7e9b410.mp4

**Comment by OleksandrHnidets** [comment]
Not reproducable

**Comment by stasgut** [comment]
Works well.
[video](https://vimeo.com/657825834)

**Comment by Nataliia-Kavaler** [comment]
Verified
