### ISSUE TITLE
[Global] Incorrect color of buttons

### ISSUE THREAD

**Issue by Sydir** [ita-social-projects/SoftServeCar-Back-End#908]
**Environment:** Android 10, Samsung A7.
**Reproducible:** always.
**Build found:** v1.0.453.

**Actual result**
Some buttons display in black color.

Example:

![incor color of button](https://user-images.githubusercontent.com/91271776/144468558-867b0dcf-2128-474f-96f5-b2da7464f22d.jpg)

**Expected result**
All buttons have the same gray color according to mock-ups.

Example:

![image](https://user-images.githubusercontent.com/91271776/144468951-50dbe80b-38a5-477d-9030-6631d109eda7.png)

**Labels to be added**
"Bug" ("bug"), Priority ("pri: low")

**Comment by Nataliia-Kavaler** [comment]
"Login" button color is black
