### ISSUE TITLE
[Global, Dark mode] Text boxes' color doesn't correspond to the mock-ups

### ISSUE THREAD

**Issue by Sydir** [ita-social-projects/SoftServeCar-Back-End#912]
**Environment:** Android 10, Samsung A7.
**Reproducible:** always.
**Build found:** v1.0.453.

**Actual result**
Text boxes' color doesn't correspond to the mock-ups. It is too light

Example:

![text area is lighter than mock-up 2](https://user-images.githubusercontent.com/91271776/144652555-c958c0f4-ea27-4c79-90f2-b8641295e1c7.jpg)

![text area is lighter than mock-up](https://user-images.githubusercontent.com/91271776/144652574-cb203804-6993-4acb-bf24-e704f84ac0c6.jpg)

**Expected result**
 Text boxes' color corresponds to the mock-ups.

Example:
![image](https://user-images.githubusercontent.com/91271776/144652671-d8c27a42-2986-46f3-8964-d8dc2bcb7142.png)

**Labels to be added**
"Bug" ("bug"), Priority ("pri: low")

**Comment by Nataliia-Kavaler** [comment]
Verified
