### ISSUE TITLE
[Preferences] Wrong number of the symbols has shown at the 'Comments' text box

### ISSUE THREAD

**Issue by Marta-Yasnuska** [ita-social-projects/SoftServeCar-Back-End#917]
Environment: Android Samsung Galaxy A 10s
Reproducible: always
Build found: android.v.1.0.458

Preconditions:
1.'Car' app is open
2. The user is logged in
3. On the app homepage go to 'My profile' menu

Steps to reproduce:
1. Go to 'Preferences'
2. Scroll down to 'Comments' text box

Actual result:
'99 symbols left' has shown under text box 

Expected result:
'Up to 100 symbols' according to the mock-up has shown under text box 

![зображення_viber_2021-12-06_18-28-47-939](https://user-images.githubusercontent.com/91321998/145253045-ada30b93-1bfd-4a9b-9932-9e9b90d364f4.jpg)
<img width="192" alt="2021-12-06 (3)" src="https://user-images.githubusercontent.com/91321998/145253062-ba2241e2-776e-4cef-8e47-2efdd2b07ea7.png">

**Comment by OleksandrHnidets** [comment]
Cannot reproduce (maybe you entered a blank space which is why it is showing 99 symbols left)

**Comment by Marta-Yasnuska** [comment]
Bug is always reproducible it's present by default, just follow all steps in a report.

**Comment by stasgut** [comment]
Cannot reproduce
[video](https://vimeo.com/657821084)
