### ISSUE TITLE
[Add address] Name of the text box is appeared when user put some values at the textbox

### ISSUE THREAD

**Issue by Marta-Yasnuska** [ita-social-projects/SoftServeCar-Back-End#919]
Environment: Android Samsung Galaxy A 10s
Reproducible: always
Build found: android.v.1.0.458

**Preconditions**
1.'Car' app is open
2. The user is logged in
3. Dark mode is chosen
3. 'My profile' menu is open

**Steps to reproduce**
1. Go to 'Address book'
2. Click on 'Add a new address'
3. At the textbox name  'Address' type some value

**Actual result**
1. 'Address' name of the text box is appears when the user put some values at the text box

**Expected result**
1.  'Address' name of the text box must disappeared when the user put some values at the text box, according to the mockup 

![зображення_viber_2021-12-06_18-28-47-749](https://user-images.githubusercontent.com/91321998/145256802-4fea2878-c516-4900-9a18-6699e3a387d6.jpg)

**Comment by Nataliia-Kavaler** [comment]
Verified
