### ISSUE TITLE
[Edit Address] Error message text do not correspond to the 'Localization' story

### ISSUE THREAD

**Issue by Marta-Yasnuska** [ita-social-projects/SoftServeCar-Back-End#923]
Environment: Android Samsung Galaxy A 10s
Reproducible: always
Build found: android.v.1.0.465

Preconditions:
1.'Car' app is open
2. The user is logged in
3. The dark theme is chosen

Steps to reproduce:
1. 'My profile' menu is open
2. Go to 'Address book' and choose the address that is previously created
3. At the 'Edit address' page press 'Remove' button at the right top corner
4.  Pop-up 'Are you sure?' is present

Actual result:
Text in the pop-up 'Do you want to delete your address information?' is not corresponding to the 'Localization' story

Expected result:
Text in the pop-up 'Are you sure you want to delete your address information?' is corresponding to the 'Localization' story

User story 
E.g.: "User story #214 
![Рисунок2](https://user-images.githubusercontent.com/91321998/145687824-7a7cf880-7766-463f-bf4e-2a981d0aaff6.jpg)

<img width="161" alt="Рисунок3" src="https://user-images.githubusercontent.com/91321998/145687803-ad5dc486-972f-4912-b1f2-d6e3e434cbb5.png">

**Comment by Nataliia-Kavaler** [comment]
Verified
