### ISSUE TITLE
[Add a ride] Pop-up "Ride successfully published", when journey does not added

### ISSUE THREAD

**Issue by RomanKuts** [ita-social-projects/SoftServeCar-Back-End#930]
Environment: Pixel XL
Reproducible: always
Build found: v1.0.428

Preconditions:

1. 'Car' app is open
2. User is logged
3. The main page is open

Steps to reproduce:

1. Go to 'Add a ride'
2. Add new journey (e.g. Lviv-Kyiv, 01.01, 12:00, Free)
3. See pop-up "Ride successfully published"
4. Create similar journey (e.g. Lviv-Kyiv, 01.01, 12:00, Free)
5. See pop-up "Ride successfully published"

Actual result:
'See pop-up "Ride successfully published", but, journey didn't add

Expected result:
'See pop-up "Ride publishing is failed"

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

**Comment by Nataliia-Kavaler** [comment]
Verified
