### ISSUE TITLE
[Login page] Wrong alignment of the welcoming text.

### ISSUE THREAD

**Issue by OlhaMyndyk** [ita-social-projects/SoftServeCar-Back-End#958]
**Environment:** Nexus 4, Android 11.0
**Reproducible:** always.
**Build found:** v1.0.502.

**Steps to reproduce**
1. Go to the 'Login' page.
2. Verify the alignment of the text on the top of the page. 

**Actual result**
1. The alignment of the "Welcome to" text is wrong.

**Expected result**
1. The "Welcome to" text is aligned as displayed on the mock-up. 

**User story and test case links**
E.g.: "User story #244

**Labels to be added**
"Bug" ("bug"), Priority ("pri: low")
![defect login](https://user-images.githubusercontent.com/96187127/149330280-707c8440-2d38-460f-a8b5-1448962c1bf6.png)
![mock-up login](https://user-images.githubusercontent.com/96187127/149330230-4ab2d8da-2e86-4420-b3e6-71cb77a48d44.PNG)

**Comment by stasgut** [comment]
tested on 4 devices, no problems detected
![4.7](https://i.ibb.co/C9kk68N/4-7.png)
![5.0](https://i.ibb.co/02sjRtp/5-0.png)
![6.3](https://i.ibb.co/92Jf4gt/6-3.png)
![5.5](https://i.ibb.co/2gm0qdJ/5-5.png)
