### ISSUE TITLE
[Address Book page] The design of the icons "Home" and "Work" is different from the mock-up. 

### ISSUE THREAD

**Issue by OlhaMyndyk** [ita-social-projects/SoftServeCar-Back-End#959]
**Environment:** Pixel 4XL, Android 10.0
**Reproducible:** always.
**Build found:** v1.0.502.

**Preconditions**
The user is logged in.

**Steps to reproduce**
1. Go to the 'My Profile' page;
2. Click on 'Address Book';
3. Add addresses with "Home" and "Work" types (e.g. "Home" - Pryrodna str., "Work" - Vasylya Stusa str.)
4. Verify the design of the icons "Home" and "Work".

**Actual result**
The design of the icons "Home" and "Work" is different from the design shown on the mock-up. 

**Expected result**
The design of the icons "Home" and "Work" is the same as shown on the mock-up. 

**User story and test case links**
E.g.: "User story #31 

**Labels to be added**
"Bug" ("bug"), Priority ("pri: low")
![Screenshot_20220113_151842](https://user-images.githubusercontent.com/96187127/149337799-70e6957a-9ab6-4fb3-be6c-520dee4fba12.png)
![mock-up addressbook](https://user-images.githubusercontent.com/96187127/149337830-06c79b12-2dc3-4287-9ca1-8903706a9741.PNG)

**Comment by Mariana0105** [comment]
The 'Other' icon of 'Address Book' must be different in Dark App Theme.
Pattern on Figma
![зображення_2022-02-04_074930](https://user-images.githubusercontent.com/96290387/152479174-7a238e34-b5c6-45f7-8ae4-2fcdae5a65cd.png)

Actual result
![зображення_2022-02-04_075033](https://user-images.githubusercontent.com/96290387/152479272-3575be5f-ee2b-42cb-8000-abf6a37f30fe.png)
