### ISSUE TITLE
[Add a Car page] Wrong alignment of the "UPLOAD PHOTO" button and color of the dropdowns containers in the dark mode.

### ISSUE THREAD

**Issue by OlhaMyndyk** [ita-social-projects/SoftServeCar-Back-End#968]
**Environment:** Pixel 4XL, Android 10.0
**Reproducible:** always.
**Build found:** android.v1.0.505

**Preconditions**
1. The 'Car' application is opened.
2. The user is logged in.
3. The dark mode is set;
4. The 'Ride Homepage' is opened.

**Steps to reproduce**
1. Go to the 'My Profile' page;
2. Tap the "My Cars" optional button;
3. Tap the "Add a Car" optional button;
4. Verify the alignment of the "UPLOAD PHOTO" button;
5. Verify the color of the dropdowns containers.

**Actual result**
1. The "UPLOAD PHOTO" button is placed in the bottom right corner of the photo container. 
2. The containers of the dropdowns are filled with a pale grey color. 

**Expected result**
1. The "UPLOAD PHOTO" button is central aligned. 
2. The containers of the dropdowns are filled with a dark-grey color. 

**User story and test case links**
E.g.: "User story #33  

**Labels to be added**
"Bug" ("bug"), Priority ("pri: low")
![Screenshot_20220117_214124](https://user-images.githubusercontent.com/96187127/149829167-fc1ea546-f2ad-4ec9-8202-ff61c0460090.png)
![uploadphoto](https://user-images.githubusercontent.com/96187127/149829187-618092b5-8002-486f-8642-a47c3563fcc4.png)

**Comment by Mariana0105** [comment]
The 'UPLOAD PHOTO' container frame in Light and Dark App Theme differs from that which is shown in the mock-up. Wrong width and color of frame line.

**Comment by Mariana0105** [comment]
Change, please, the colour of frame in Light App Theme.

![зображення_2022-02-01_013659](https://user-images.githubusercontent.com/96290387/151890658-2a321de3-2e1d-47cd-aa53-37b5e7891117.png)
Actual result
![зображення_2022-02-01_013846](https://user-images.githubusercontent.com/96290387/151890826-20dc7ec3-9537-4be1-a338-472a0cc476b9.png)
