### ISSUE TITLE
[Global] The background of the page is not blurred when a pop-up appears. 

### ISSUE THREAD

**Issue by OlhaMyndyk** [ita-social-projects/SoftServeCar-Back-End#970]
Environment: Pixel 4XL, Android 10.0
Reproducible: always.
Build found: android.v1.0.505

**Preconditions**
1. The "Car" application is opened;
2. The user is logged in;
3. The "Ride Homepage" is opened.

**Steps to reproduce**
1. Tap "Add a ride";
2. Set any address into the "From" search box and press the "Confirm" button;
3. Tap the "Back" button;

**Actual result**
The background of the page is not blurred when a pop-up appears.

**Expected result**
The background of the page is blurred when a pop-up appears. 

**User story and test case links**
E.g.: "User story #

**Labels to be added**
"Bug" ("bug"), Priority ("pri: low")
![Screenshot_20220117_222959](https://user-images.githubusercontent.com/96187127/149970112-075c75f9-b20c-451b-938c-c04021d3f88a.png)
![pop-upaddaride](https://user-images.githubusercontent.com/96187127/149970290-acb23913-6972-4d59-a62c-0b0150196368.PNG)

**Comment by RomanVynarovych** [comment]
The decision was made to refuse to "blur" because of difficult realisation.
